### ISSUE TITLE
Dripsy's Button does not work with variants

### ISSUE THREAD

**Issue by harrisrobin** [nandorojo/dripsy#103]
I made a codesandbox to reproduce: 
https://codesandbox.io/s/relaxed-spence-vtprq?file=/src/App.js

Despite defining `buttons` in my theme, passing variants to the `<Button />` component from `dripsy` does not change the styles. Any ideas? 

```
Dripsy version: ^2.1.0
```

**Comment by nandorojo** [comment]
Hey @harrisrobin, thanks for the issue.

Yeah, it's confusing that this is involved in the package at all. I should remove it.

You can see my temporary solution here: https://github.com/nandorojo/dripsy/issues/59#issuecomment-731614281

**Comment by nandorojo** [comment]
If you want to use a custom button, like from `react-native-paper`, you can use the `useSx` prop that will be in the next version. See #23

**Comment by nandorojo** [comment]
Just released v2.2.0 with support for `useSx`: https://github.com/nandorojo/dripsy/releases/tag/v2.2.0
