### ISSUE TITLE
`defaultVariant = 'primary'` leads to unpredictable results

### ISSUE THREAD

**Issue by nightwind2020** [nandorojo/dripsy#104]
I made a [demo](https://codesandbox.io/s/dripsy-default-variant-catch-unexcepted-result-28mj3?file=/src/index.tsx)  to reproduce the problem.

Related code:
https://github.com/nandorojo/dripsy/blob/030b06d9532032989d3d97a7c9c9dff7ae0ef923/packages/core/src/css/map-props.ts#L13

**Comment by nandorojo** [comment]
Interesting. Yeah you're probably right. Let me just look through my app to confirm that's fine for me but it should be good to take out.

**Comment by nandorojo** [comment]
Want to send a PR for me removing that?
