### ISSUE TITLE
npm crashes while attempting to install dripsy 

### ISSUE THREAD

**Issue by Symasia** [nandorojo/dripsy#105]
This is the error output I received:

```npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path %ROOT_DIR%\node_modules\@artsy\fresnel
npm ERR! dest %ROOT_DIR%\node_modules\@artsy\.fresnel.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename '%ROOT_DIR%\node_modules\@artsy\fresnel' -> %ROOT_DIR%\node_modules\@artsy\.fresnel.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Could be due to something that happened while dropping SSR support #100 : 
> `yarn add dripsy`, v2.0.1 removes fresnel and SSR.

PS: %ROOT_DIR% is a placeholder.

**Comment by nandorojo** [comment]
Weird, I haven't seen this. What are more details about your environment? I'm using Dripsy's latest version without any issues.

**Comment by Symasia** [comment]
Nuked my lock file and node_modules and I could install it without crashing. Thank you for the quick response :+1:. I'll be closing this because my issue was solved.
