### ISSUE TITLE
`ssr={true}` disables SSR?

### ISSUE THREAD

**Issue by redbar0n** [nandorojo/dripsy#106]
I was just thinking, passing `ssr={true}` gives the impression that it enables or works with SSR.

But from what I can understand it actually disables SSR? Or makes sure that Dripsy components circumvent SSR?

If so, it might be better to name the `ssr` prop to `disableSSR`, for instance?

**Comment by nandorojo** [comment]
I would be open to a PR changing this to `disableSSR`. It could mark `ssr` as deprecated, but keep it until the next major version change. I'll close this for now since there's no movement on it, but I'll merge a PR.
