### ISSUE TITLE
EventEmitter deprecated in React Native 0.65

### ISSUE THREAD

**Issue by NickMandylas** [nandorojo/dripsy#113]
Receiving a deprecation warning for Dripsy.Text:

```
EventEmitter.removeListener('change', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`. 
Dripsy.Text@http://192.168.114.127:8081/...
```

Specific code that it is referencing with deprecation notice is this:

```typescript
const Subtitle = () => (
  <Text
    variant="thick.h1"
    sx={{
      color: titleColor ? titleColor : secondaryColor,
      marginBottom: 1,
    }}>
    {subtitle}
  </Text>
);
```

Deprecation notice is referring to this change: https://github.com/facebook/react-native/commit/14f7a2b70754c92804d746959d1ff091bf49af69

**Comment by nandorojo** [comment]
I’m a bit confused, we don’t use EventEmitter as far as I know. Are you sure this is relevant to Dripsy?

**Comment by nandorojo** [comment]
I wonder if this it’s used under the hood for the Dimensions API.

**Comment by NickMandylas** [comment]
You are right, my bad! I'm changing the Subtitle component based off the current index of a slider component, which is taken calculated from Dimensions. Got a bit confused with the console output, but the stack trace shows that Dimensions at fault. 

Thanks for the quick response 🙂

**Comment by JackCA** [comment]
I am seeing this on react-native 0.65.1 and in my case, is coming from this [line](https://github.com/nandorojo/dripsy/blob/master/packages/core/src/css/use-breakpoint-index.ts#L127) 

It's marked as deprecated:

![CleanShot 2021-09-29 at 09 36 36](https://user-images.githubusercontent.com/296167/135311608-a33162ab-6c5b-41af-aa08-e6f0556d867d.png)

**Comment by nandorojo** [comment]
Ah I see, so there’s a breaking change in 65. I’ll try to account for this in v3. What’s the replacement in 65 for that function?

**Comment by JackCA** [comment]
> Ah I see, so there’s a breaking change in 65. I’ll try to account for this in v3. What’s the replacement in 65 for that function?

I believe you need to keep a [reference to the object returned from `addEventLIstener`](https://github.com/nandorojo/dripsy/blob/master/packages/core/src/css/use-breakpoint-index.ts#L119) and call `remove` on that

**Comment by nandorojo** [comment]
<img width="935" alt="Screen Shot 2021-09-29 at 5 15 13 PM" src="https://user-images.githubusercontent.com/13172299/135349507-4db2f561-fff8-470b-b60a-c07afdf7c846.png">

I see, so this should do it. Will push to the v3 `@canary`

**Comment by nandorojo** [comment]
Published: `yarn add dripsy@canary`. Please keep up to date with changes to v3 at https://github.com/nandorojo/dripsy/pull/124

You can also see the upgrade guide at https://github.com/nandorojo/dripsy/pull/124 to take advantage of the new features (it should all be backwards compatible).

**Comment by nandorojo** [comment]
The version that works for me is `3.0.0-alpha.39` (I just published again)
