### ISSUE TITLE
Cannot Compile Project (NextJS + Expo + Typescript)

### ISSUE THREAD

**Issue by JayPerfetto** [nandorojo/dripsy#118]
After adding Dripsy and following the setup instructions, I am faced with the following compilation error:

![Screen Shot 2021-08-18 at 12 29 40 PM](https://user-images.githubusercontent.com/34031697/129960361-cfda4bf3-b039-4e35-a89c-f206302ece07.png)

my _app.tsx is here:
![Screen Shot 2021-08-18 at 12 31 14 PM](https://user-images.githubusercontent.com/34031697/129960470-d3257c1c-e38c-40e1-9316-66d7cb2f568d.png)

my next.config.js:
![Screen Shot 2021-08-18 at 12 32 25 PM](https://user-images.githubusercontent.com/34031697/129960608-777ba1b6-ca48-484c-9b8f-31cfa19a3475.png)

I also tried the workaround adding a custom webpaci.config.js to no avail - any suggestions? Tested/Facing this issue on all versions back to 2.2.0

**Comment by nandorojo** [comment]
Hm what version of next? It’s working for me on Dripsy@2.2.0 and next@10.2.3-canary.1.

@axeldelafosse has been working on Next.js 11 support for Expo too.

Does your app work without Dripsy?

**Comment by nandorojo** [comment]
I’m also on next-transpile-modules@6.4.0, haven’t tested beyond that.

**Comment by JayPerfetto** [comment]
here is my Package.json - expo / next are the versions currently shipping when you create a new expo app using their example command "npx create-react-native-app -t with-nextjs"

`{
  "name": "expo-next",
  "version": "0.1.0",
  "dependencies": {
    "@nandorojo/swr-firestore": "^0.16.0",
    "dripsy": "^2.2.0",
    "expo": "~42.0.0",
    "expo-av": "~9.2.3",
    "expo-next-react-navigation": "^1.2.1",
    "firebase": "8.2.3",
    "lodash": "^4.17.21",
    "lodash.debounce": "^4.0.8",
    "lodash.kebabcase": "^4.1.1",
    "next": "11.1.0",
    "next-fonts": "^1.5.1",
    "next-images": "^1.8.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-firebase-hooks": "^3.0.4",
    "react-helmet": "^6.1.0",
    "react-hook-form": "^7.12.2",
    "react-hot-toast": "^2.1.0",
    "react-markdown": "^7.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-web": "^0.17.1",
    "sass": "^1.37.5",
    "setimmediate": "^1.0.5",
    "tailwind-react-native-classnames": "^1.4.2"
  },
  "devDependencies": {
    "@babel/core": "^7.14.6",
    "@expo/config": "^5.0.7",
    "@expo/next-adapter": "^3.0.1",
    "@expo/webpack-config": "^0.14.0",
    "@types/lodash.debounce": "^4.0.6",
    "@types/lodash.kebabcase": "^4.1.6",
    "@types/react": "17.0.18",
    "@types/react-helmet": "^6.1.2",
    "@types/react-native": "~0.63.2",
    "autoprefixer": "^10.3.1",
    "babel-plugin-module-resolver": "^4.1.0",
    "eslint": "7.32.0",
    "eslint-config-next": "11.1.0",
    "next-compose-plugins": "^2.2.1",
    "next-transpile-modules": "^8.0.0",
    "postcss": "^8.3.6",
    "tailwindcss": "^2.2.7",
    "typescript": "4.3.5"
  },
  "scripts": {
    "start": "next dev",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "build": "next build",
    "export": "next export",
    "lint": "next lint",
    "fb-emulate": "cd functions && npm run build  && cd .. && firebase emulators:start",
    "kill-emulators": "lsof -ti tcp:9099 | xargs kill && lsof -ti tcp:5001 | xargs kill && lsof -ti tcp:8080 | xargs kill && lsof -ti tcp:8085 | xargs kill && lsof -ti tcp:9199 | xargs kill"
  },
  "private": true
}
`

**Comment by JayPerfetto** [comment]
Which version of @expo/next-adapter are you using? It seems like theres a dependency gap between 2.1.8x and 3.x.x where it won't allow me to use a peer dependency of next@10x, only 9 or 11

**Comment by nandorojo** [comment]
Yeah I’m on 2.1.x with next 10. You’ll just need to add the class plug-in properties to your Babel config.

**Comment by JayPerfetto** [comment]
Would you mind giving me a pointer on that one? I'm somewhat new to react - here is my babel.config.js

```
// @generated: @expo/next-adapter@2.1.52
// Learn more: https://docs.expo.io/guides/using-nextjs/

module.exports = {
  presets: ["@expo/next-adapter/babel"],
  plugins: [
    [
      "module-resolver",
      {
        root: ["./src"],
        extensions: [".ios.js", ".android.js", ".js", ".ts", ".tsx", ".json"],
        alias: {
          tests: ["./tests/"],
          "@components": "./components",
          "@styles": "./styles",
          "@models": "./models",
          "@interfaces": "./interfaces",
          "@enums": "./enums",
        },
      },
    ],
  ],
};

```

**Comment by nandorojo** [comment]
Yeah sure, Babel is confusing at first.

Install this library:

`@babel/plugin-proposal-class-properties`

Then add it to your `plugins` array in your Babel config.

Finally, I recommend using the latest 2.1 version of the expo next adapter with Next 10.1. That’s working well for me.

Alternatively, if you want to use Next 11.0 (Next 11.1 isn’t tested yet as far as I know), I suggest you set it up according to the particular specs from this example: https://github.com/axeldelafosse/expo-next-monorepo-example

You don’t need to make a monorepo, but the pieces are there to use Next.js 11. @axeldelafosse made that great example. You’ll want to look at the Babel files, next config, etc.

If you have more issues related to Expo when it comes to Next 11, I do recommend chiming in on this issue too: https://github.com/expo/expo-cli/issues/3579

The community can help a lot there too if the issue goes beyond a simple Dripsy setup.

**Comment by nandorojo** [comment]
But given that you say it works without Dripsy, I'm definitely curious what the issue is.

Can you try those versions of next and expo/next-adapter and let me know if it works?

**Comment by nandorojo** [comment]
We are working on making Next.js be a much smoother out of the box with React Native Web. But we’re still ironing out some details as Next.js makes some rapid changes.

**Comment by JayPerfetto** [comment]
No dice simply reverting NextJS and the adapter versions, that pushes the builder to use Webpack 4 instead of 5 which throws a new build error launching 'next dev'. I'll give the babel changes a try with the original versions of next / adapter (11/3) and let you know - thanks for your help!!
![Screen Shot 2021-08-18 at 1 11 03 PM](https://user-images.githubusercontent.com/34031697/129965470-91f3bc05-ce87-424a-a011-a8f9d5f3e361.png)

**Comment by nandorojo** [comment]
Be sure to delete node modules and .next in between these versions changes. Otherwise you get stuck with a broken cache.

**Comment by JayPerfetto** [comment]
I tried pulling down the code to that mono-repo example and noticed that it does not come with Dripsy installed - I tried to install it based on the instructions in that repo (adding it to the Expo dir's package.json), and I get a similar error to the one I reported when launching the NextJS app (prior to adding Dripsy it worked and I saw the Hello World screen)
![Screen Shot 2021-08-18 at 1 41 51 PM](https://user-images.githubusercontent.com/34031697/129969367-6a390baf-26da-45ce-abf3-e4ce99161783.png)

**Comment by nandorojo** [comment]
Hmm, did you try with the versions I mentioned?

next 10.1
next-transpile-modules 6.4.0
expo adapter 2.1.x

**Comment by JayPerfetto** [comment]
Which versions are you using specifically? I get a peer dependency error when I use this combination - is "--legacy-peer-deps" safe to use in this scenario?
```
npm ERR! Found: next@10.1.0
npm ERR! node_modules/next
npm ERR!   next@"10.1.0" from the root project
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^9" from @expo/next-adapter@2.1.83
npm ERR! node_modules/@expo/next-adapter
npm ERR!   dev @expo/next-adapter@"^2.1.83" from the root project
```

**Comment by nandorojo** [comment]
Yeah I always use legacy peer deps. In fact, I use yarn v1, which doesn’t auto install peer deps. I find the new peer dep method annoying.

**Comment by JayPerfetto** [comment]
This combination of dependencies forces Expo to build using webpack 4, which clearly won't work without additional configuration. The project does not compile and it fails building native expo-next components. I am going to leave this for now, unfortunately I can't waste any more time on this today - let me know if you're ever to get an example working on next 11 and the latest versions of Expo / RN / Next-adapters

Thanks for your time today, sorry no resolution could be reached
![Screen Shot 2021-08-18 at 2 02 03 PM](https://user-images.githubusercontent.com/34031697/129971725-491a8fbe-ab1d-4313-80f1-f392dbdaabcd.png)

**Comment by nandorojo** [comment]
Oh I know this error!

try adding the Babel plug-in I mentioned earlier. That should do it :)

**Comment by nandorojo** [comment]
This one https://github.com/nandorojo/dripsy/issues/118#issuecomment-901394895

**Comment by nandorojo** [comment]
But yeah you will need to use webpack 4 for that to work. I’ll share here if we get webpack 5 / next 11.1 to be stable with expo.

I’m release the iPhone app this week for beatgig.com, so I’ve been focused on Native over web this month, but I’ll be more focused on web soon and will revisit upgrading Next.

Thanks!

**Comment by JayPerfetto** [comment]
I had success finally getting the older version combo to compile using Webpack 4 (without adding Dripsy yet), but then as soon as I did and added it to my list of next-transpile-modules, I got this, again on that same NativeActivityIndicator component

![Screen Shot 2021-08-18 at 2 14 34 PM](https://user-images.githubusercontent.com/34031697/129973161-c0dec563-2196-4419-acde-0645e6f31d64.png)

**Comment by nandorojo** [comment]
Oof, that’s interesting. Assuming you’ve installed the *exact* versions I’ve mentioned, I’m a bit stumped for now.

**Comment by nandorojo** [comment]
Oh wait! Try React 16.8.3

**Comment by JayPerfetto** [comment]
I think that may be the trick finally! Looks like we have compiled with DripsyProvider wrapping my app and a default empty theme :)

Thank you!! 

Here is my final Package.json for all those who come here from starting on a new Expo project!:

```
{
  "name": "expo-next",
  "version": "0.1.0",
  "dependencies": {
    "@babel/plugin-proposal-class-properties": "^7.14.5",
    "@nandorojo/swr-firestore": "^0.16.0",
    "dripsy": "^2.3.6",
    "expo": "~42.0.0",
    "expo-av": "~9.2.3",
    "expo-next-react-navigation": "^1.2.1",
    "firebase": "8.2.3",
    "lodash": "^4.17.21",
    "lodash.debounce": "^4.0.8",
    "lodash.kebabcase": "^4.1.1",
    "next": "10.1.0",
    "next-fonts": "^1.5.1",
    "next-images": "^1.8.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-firebase-hooks": "^3.0.4",
    "react-helmet": "^6.1.0",
    "react-hook-form": "^7.12.2",
    "react-hot-toast": "^2.1.0",
    "react-markdown": "^7.0.0",
    "react-native": "0.65.0",
    "react-native-web": "^0.17.1",
    "sass": "^1.37.5",
    "setimmediate": "^1.0.5",
    "tailwind-react-native-classnames": "^1.4.2"
  },
  "devDependencies": {
    "@babel/core": "^7.14.6",
    "@expo/config": "^5.0.7",
    "@expo/next-adapter": "^2.1.83",
    "@types/lodash.debounce": "^4.0.6",
    "@types/lodash.kebabcase": "^4.1.6",
    "@types/react": "17.0.18",
    "@types/react-helmet": "^6.1.2",
    "@types/react-native": "~0.63.2",
    "autoprefixer": "^10.3.1",
    "babel-plugin-module-resolver": "^4.1.0",
    "eslint": "7.32.0",
    "eslint-config-next": "11.1.0",
    "next-compose-plugins": "^2.2.1",
    "next-transpile-modules": "^6.4.0",
    "postcss": "^8.3.6",
    "tailwindcss": "^2.2.7",
    "typescript": "4.3.5"
  },
  "scripts": {
    "start": "next dev",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "build": "next build",
    "export": "next export",
    "lint": "next lint",
    "fb-emulate": "cd functions && npm run build  && cd .. && firebase emulators:start",
    "kill-emulators": "lsof -ti tcp:9099 | xargs kill && lsof -ti tcp:5001 | xargs kill && lsof -ti tcp:8080 | xargs kill && lsof -ti tcp:8085 | xargs kill && lsof -ti tcp:9199 | xargs kill"
  },
  "private": true
}

```

**Comment by louisgv** [comment]
Just wanted to drop-by and comment that webpack5 doesn't seem to play well with modules coming from next-transpile-module that has react-native in it. I also had to switch back to webpack4, but with that I was able to use next11. For more info: 

https://github.com/expo/expo-cli/issues/3579#issuecomment-902472571

**Comment by axeldelafosse** [comment]
> Alternatively, if you want to use Next 11.0 (Next 11.1 isn’t tested yet as far as I know), I suggest you set it up according to the particular specs from this example: https://github.com/axeldelafosse/expo-next-monorepo-example

I'm using 11.1 now and it's working well! Thanks for sharing the example @nandorojo 

> Just wanted to drop-by and comment that webpack5 doesn't seem to play well with modules coming from next-transpile-module that has react-native in it

Can you share a reproducible repo @louisgv, please? It should work

> I tried pulling down the code to that mono-repo example and noticed that it does not come with Dripsy installed - I tried to install it based on the instructions in that repo (adding it to the Expo dir's package.json), and I get a similar error to the one I reported when launching the NextJS app (prior to adding Dripsy it worked and I saw the Hello World screen)

@JayPerfetto I think you forgot to transpile `dripsy`:

```
const withTM = require('next-transpile-modules')([
  'app',
  '@gorhom/bottom-sheet',
  '@gorhom/portal',
  'dripsy',
  '@dripsy/core'
]);
```

Sorry I know this isn't very convenient... Would it be useful if I added Dripsy to the example? Is this a good idea?

**Comment by axeldelafosse** [comment]
Just added Dripsy to the example because it's the best way to style a universal React app but seems to be pretty confusing to set up. Also upgraded to Next.js 11.1 👍

**Comment by nandorojo** [comment]
Thanks @axeldelafosse! Maybe we could link to this on the Dripsy readme for Next.js 11 usage.

**Comment by JayPerfetto** [comment]
@axeldelafosse thanks a ton for your great updates to your monorepo framework - I got everything working today using that with it's updated dependencies, and I think one major missing link for me in my newness to react-native / next was that I was using NPM instead of Yarn. The yarn commands / using yarn add to install my dependencies seems like a pretty critical thing to call out in the docs, is that fair to say? 

For anyone else really new to this, check out docs here:

**Comment by nandorojo** [comment]
Good point. I take that for granted now. Yarn is much better IMO.

**Comment by iynaix** [comment]
FWIW, I added the following override to my .babelrc and it worked! (Only took a couple of hours :sweat_smile:) 

I'm using Next 11.1 with webpack 5, no monorepo.

```js
module.exports = {
    presets: ["@expo/next-adapter/babel"],
    overrides: [
        {
            test: "./node_modules/dripsy/*",
            plugins: ["@babel/plugin-transform-react-jsx"],
        },
    ],
}
```
