### ISSUE TITLE
styled method aspectRatio property type invalid

### ISSUE THREAD

**Issue by demic-dev** [nandorojo/dripsy#132]
Hi!

When you declare a component with the `styled` method and you give them styling, aspectRatio property is set as string, but React Native requires a number.

<img width="981" alt="Screenshot 2021-10-15 at 22 55 28" src="https://user-images.githubusercontent.com/59309595/137552400-4a3fabba-637f-4f35-8418-47945a285a5f.png">

### Workaround

Commenting the line before with `@ts-ignore` can avoid the problem. Example:

```jsx
const Image = styled(Image)({
  width: 300px,
  // @ts-ignore
  aspectRatio: 1
});
```

**Comment by demic-dev** [comment]
Yes, with the latest version is working fine, thanks for the quick response!

**Comment by nandorojo** [comment]
Cool
