### ISSUE TITLE
Recursive `styled` components lose `ThemeKey` generic

### ISSUE THREAD

**Issue by Jomik** [nandorojo/dripsy#152]
I am unsure how I would expect it to work, but may make sense to somehow prevent with types or mention this incompatibility.

I created a simple `Divider`, which works as expected, but gives a typescript error when trying to use it with a different variant.
```tsx
import { styled, View } from 'dripsy';

export const Divider = styled(View, {
  themeKey: 'divider',
  defaultVariant: 'horizontal',
})({
  bg: '$divider',
});
```
Related theme variant:
```ts
  divider: {
    horizontal: {
      height: 'divider',
      width: '100%',
    },
    vertical: {
      width: 'divider',
      height: '100%',
    },
  },
```
![image](https://user-images.githubusercontent.com/699655/141677456-e189237d-2be4-4c30-bced-8b1b07f3c573.png)
Importing `View` from react-native when creating `Divider` solves this problem completely and has no issues.

I have no issues with this, just figured I would let you know so we can avoid other users potentially having the same issue :)

**Comment by nandorojo** [comment]
Hey! This is because divided isn’t a valid theme key.

**Comment by Jomik** [comment]
> Hey! This is because divided isn’t a valid theme key.

It works just fine, with `View` imported from React Native?
What do you mean it isn't supported?

**Comment by nandorojo** [comment]
Oh, I misunderstood. I see now. It must be because we’re clashing generics between views. Good catch. I’ll have to see if we can work around this (perhaps by omitting the previous one)

**Comment by nandorojo** [comment]
I'm not totally sure how to work around this. In most cases, we _want_ a recursive `styled` to inherit the variant etc of its parent...it seems like the only exception is when we're setting a custom `themeKey`. I think I would make my recommendation, for now, to use `react-native` as the building block. I would certainly be open to a solution, I'm just not sure how to implement it without negative consequences.

**Comment by nandorojo** [comment]
I think I'm going to close this, and recommend using `react-native` for your imports of custom components when you're using a `themeKey`. There may be a solution, but I don't really have time for it since there's already a working option. Thanks for the issue though!

**Comment by Jomik** [comment]
Makes perfect sense for me 💪
I was thinking of simply adding it to the docs.
If you want, I might have time to create a PR.
Though it's a very minor issue 😅

**Comment by nandorojo** [comment]
Yeah go for it!
