### ISSUE TITLE
What are the best practice for style composition?

### ISSUE THREAD

**Issue by Wuyialex** [nandorojo/dripsy#157]
Currently, dripsy's sx prop does not allow arrays, so it is using object spread. Is there any problem with dripsy's optimization after doing this? Or is there another recommended way?

```
// StyleSheet, View
 <View style={[styles.box, style]} />

// dripsy's View
 <View sx={{ color: '$grey', ...style }} />
```

**Comment by nandorojo** [comment]
A spread like that works fine. For TS support, you can import the `Sx` type.
