### ISSUE TITLE
Heading (H1, H2, H3, ...) doesn't apply the custom fontWeight property

### ISSUE THREAD

**Issue by alexis-regnaud** [nandorojo/dripsy#160]
I use `customFont` and try to change the default `fontWeight` for each heading within the theme, but it is not applied.

This is an example with `<H1>` and `<Text variant="h1">` :

- theme: 
![image](https://user-images.githubusercontent.com/15250423/147497670-078b7377-c558-42ea-ad33-60f8ff801757.png)

- code: 
![image](https://user-images.githubusercontent.com/15250423/147497631-36de157d-a50e-4787-a918-f3e07f73374f.png)

- app:
![image](https://user-images.githubusercontent.com/15250423/147497745-70450b70-4548-42fe-9375-1e276dfaba82.png)

Only `<Text>` has the correct `fontWeight`

**Comment by nandorojo** [comment]
Is this on Android?

**Comment by alexis-regnaud** [comment]
Yes

**Comment by nandorojo** [comment]
Yeah it’s a known bug, it’s because expo/html-elements sets fontWeight when it shouldn’t. The solution would be to copy the expo components into Dripsy. I’d be happy to review a PR.

**Comment by levic92** [comment]
Here is another solution that is working for me. Setting the fontWeight to `normal` in the style prop:

`<H1 style={{fontWeight: "normal"}}>Title</H1>`

**Comment by nandorojo** [comment]
I think I'm going to close this since it's an issue with `@expo/html-elements`. Or maybe we apply that style under the hood as @levic92 mentioned.
