### ISSUE TITLE
Using Variant on 3rd party components

### ISSUE THREAD

**Issue by thegitparticle** [nandorojo/dripsy#169]
I am trying to use variant as per [this](https://www.dripsy.xyz/usage/theming/variants#variants-on-any-component)  on `<FastImage />` component from [here](https://github.com/DylanVann/react-native-fast-image) and it does not work.

Does variants work only on react native's first party components imported from {Dripsy} only?

**Comment by nandorojo** [comment]
It should work. can you share the code? also, do the styles work when you apply them directly to the fast image?

**Comment by thegitparticle** [comment]
Yes, it works when applied directly - this way
`<FastImage
            source={{
              uri: props.coinDetails.image,
              priority: FastImage.priority.normal,
            }}
            resizeMode={FastImage.resizeMode.contain}
            // variant="images.small_icon_30_round"
            style={sxCustom({width: 30, height: 30, borderRadius: 15})}
          />`


Not when using variant

`
<FastImage
            source={{
              uri: props.coinDetails.image,
              priority: FastImage.priority.normal,
            }}
            resizeMode={FastImage.resizeMode.contain}
            variant="images.small_icon_30_round"
          />
`

Dripsy theme - images part:

`
images: {
    small_icon_30_round: {
      width: 30,
      height: 30,
      borderRadius: 15,
    },
  },
`

**Comment by thegitparticle** [comment]
`
const StyledFastImage = styled(FastImage)({
  width: 30,
  height: 30,
  borderRadius: 15,
});
`

This worked

**Comment by thegitparticle** [comment]
No, it does not work Image imported from r-n. It works only with Image from dripsy

**Comment by thegitparticle** [comment]
I am currently going ahead with styled way of doing things. 

I can make a expo snack, but will need some time
