### ISSUE TITLE
Module '"dripsy"' has no exported member 'makeTheme'.

### ISSUE THREAD

**Issue by adherb** [nandorojo/dripsy#170]
Hello,

I am using the expo-next-monorepo-example. In the theme.ts file in the app folder I have the following code:

```
import { makeTheme } from 'dripsy';

const theme = makeTheme({
  colors: { primary: 'blue' }
});

type MyTheme = typeof theme;

declare module 'dripsy' {
  interface DripsyCustomTheme extends MyTheme {}
}

export { theme };
```

I am getting the following error: Module '"dripsy"' has no exported member 'makeTheme'.

Is there a way to fix this?

**Comment by nandorojo** [comment]
you’ll need to upgrade dripsy
