### ISSUE TITLE
Question - Regarding design-system

### ISSUE THREAD

**Issue by dittmarconsulting** [nandorojo/dripsy#177]
Hi Dripsy team,

In my current mono-repo I have incorporated this library https://styled-system.com so that I can use it on web and RN.

I'm wondering whether there is a way for me to use `Dripsy` together with `styled-system`?

I would rather try out you library than use `react-native-web`.

Thank you in advance,

Tom

**Comment by nandorojo** [comment]
Dripsy is based on Styled System, but it uses react native web under the hood. I don’t think styled system itself will work on native, but dripsy will work on both web and native.

**Comment by dittmarconsulting** [comment]
Hi @nandorojo,

Thank you for your `super fast` response. Much appreciated.

Btw, `styled-system` works perfectly in `react native`. In fact, I have been using it in all my apps so far. It's also good to know that `Dripsy` is using `react-native-web` under the hood. 

Again, thank you so much for the info.

**Comment by nandorojo** [comment]
Oh, nice, that's good to know. what does that mean though? are you using it with `styled-components`?

**Comment by dittmarconsulting** [comment]
Sorry for the delay @nandorojo 

I'm using `styled-system`, which in turn uses `styled-components` under the hood.

Here is a very basic core component `Image`

```js
import styled from 'styled-components/native'
import { color, layout, position, system } from 'styled-system'

import { ImageProps } from './types'

const Image = styled.Image<ImageProps>`
  ${color}
  ${layout}
  ${position}
  ${system({
    tintColor: true
  })}
`
export default Image
```

I have now successfully converted that component and use it in mobile (Android & iOS) and web (`NextJS`)

In my component, I have now access to the injected props from `styled-system`. It would look like that

```js
<Image width={100} height={100} source={<some source>} />
```

It's similar to Dripsy but I really like the `styled-system` approach.

**Comment by nandorojo** [comment]
okay now i understand, it uses styled components like i thought.

**Comment by nandorojo** [comment]
dripsy kind of does what styled system does in an easier way. it's based on theme-ui from react. theme-ui is made by the creator of styled-system.
