### ISSUE TITLE
User agent styles override react native styles causing unintended behavior when using as prop

### ISSUE THREAD

**Issue by cmaycumber** [nandorojo/dripsy#18]
For example when applying as="section" to a <View/> component. This automatically applies display="block" styling to the section and overrides the default view styles.

One potential solution may be to leverage a component creation method similar to @expo/html-elements or use them directly.

**Comment by nandorojo** [comment]
Interesting. Is there a strong use-case for using native HTML elements in React Native? I would recommend sticking to React Native/React Native Web primitives only, to maintain strict style parity across platforms.

**Comment by cmaycumber** [comment]
That's a valid point. I don't have a strong case for it. I think that sticking to primitives, in general, is the best option. I think that we should mention this in the docs so that someone doesn't accidentally think this is a bug. I'm going to close this for now.

**Comment by nandorojo** [comment]
Good point. We could throw a warning in dev mode if the user passes a string for the `as` prop.

**Comment by cmaycumber** [comment]
That's a super good idea. I'll open a new issue to add that in.
