### ISSUE TITLE
Support for the experimental syntax 'jsx' isn't currently enabled

### ISSUE THREAD

**Issue by keithpickering** [nandorojo/dripsy#180]
This runtime error is thrown whenever I call `makeTheme` even if I don't include the wrapper component. It's a standard create-react-app setup so I'm not able to change the babel config. Are there any instructions for configuring Dripsy with CRA?

**Comment by nandorojo** [comment]
can you check out this issue? https://github.com/nandorojo/dripsy/issues/92
