### ISSUE TITLE
Duplicate Identifier

### ISSUE THREAD

**Issue by seanaguinaga** [nandorojo/dripsy#182]
Looks like there is a conflict with TypeScript?

Any ideas on how to overload?
<img width="1404" alt="Screen Shot 2022-03-07 at 11 16 22" src="https://user-images.githubusercontent.com/15254340/157102507-5a25a756-b041-4ef2-b109-f580d43f64ea.png">

**Comment by nandorojo** [comment]
your declaration merging isn’t following the docs correctly. it should be an interface, not a type

**Comment by seanaguinaga** [comment]
Thank you!

Stole this from an expo/next monorepo, will update it there too

**Comment by nandorojo** [comment]
cool! which monorepo?

**Comment by seanaguinaga** [comment]
This one: https://github.com/team-nimble/smd

Worked great for me, I made an nx workspace repo from this successfully, all the others I tried never worked as a base
