### ISSUE TITLE
Support paddingHorizontal/vertical and marginHorizontal/vertical

### ISSUE THREAD

**Issue by hirbod** [nandorojo/dripsy#189]
Hi @nandorojo,

while I know `sx` has "px, py, mx, my", I still think that TypeScript should not complain when using the react-native names, unless you have a real reason why which I am not aware of.

Because using them works just fine, just the Types are missing (in this case are aliased).
I do like the abbreviation, but sometimes I am "porting" stuff and this forces me to refactor.

What do you think?

**Comment by nandorojo** [comment]
Yeah fair point, I just have to see if it's easy to add

**Comment by nandorojo** [comment]
Fixed in `3.6.1`

**Comment by nandorojo** [comment]
Actually there may be a regression here, if it's too complex to fix in a short amount of time I may have to revert for now.

**Comment by hirbod** [comment]
It is not a big deal, no worries. If it cause more pain than just ignore it.

**Comment by nandorojo** [comment]
Pretty sure I fixed it all now, `yarn add dripsy@canary` for `3.6.2` should have it.
