### ISSUE TITLE
`sizes` not working properly on mobile native

### ISSUE THREAD

**Issue by rafaelrinaldi** [nandorojo/dripsy#191]
I am trying to use `sizes` to specify the `height` of a `Pressable`. It works fine on the browser, but I can't seem to make it work for mobile native other than inlining the value itself.

```ts
// theme.ts
export const theme = makeTheme({
  /* ... */
  sizes: {
    $0: 0,
    $1: 4,
    $2: 8,
    $3: 12,
    $4: 16,
    $5: 20,
    $6: 24,
    $7: 32,
    $8: 40,
  }
  /* ... */
})
```
```tsx
// Button.tsx
const Button = ({ children, variant = 'primary' }) => (
    <Pressable
      sx={{
          variant: `buttons.${variant}`,
          justifyContent: 'center',
          backgroundColor: 'red',
          height: '$8'
       }}>
        {children}
</Pressable>
)
```

Browser output:
<img width="171" alt="Untitled" src="https://user-images.githubusercontent.com/87162/160937088-b6ac5d45-23ea-445c-8a07-4977a46db57b.png">

iOS Simulator error:
<img width="456" alt="Untitled" src="https://user-images.githubusercontent.com/87162/160937160-58151129-0673-4689-a674-53cb0603f93c.png">

Am I doing something wrong?

**Comment by nandorojo** [comment]
yeah something is probably wrong here. can you try making sx a function of your theme and log it?

**Comment by nandorojo** [comment]
any luck?
