### ISSUE TITLE
Margin and Padding lower than 9px powers its value when using sx or styled

### ISSUE THREAD

**Issue by brduck** [nandorojo/dripsy#194]
In our project, we're using `dripsy` within a `styles.ts` file theming everything with `styled` similar to `styled-components`. ex: 
```ts
import { styled } from 'dripsy'
import { Text, View } from 'react-native'

export const Container = styled(View)((_props) => ({
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: '#e03d26',
  borderRadius: 5,
}))
```

But when I set margin or padding the final code get it's value powered (happens on Next and Expo), examples:

## Example 1 
Padding with 8px using `styled()`

Code (8px):
```ts
export const Container = styled(View)((_props) => ({
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: '#e03d26',
  borderRadius: 5,
  padding: 8
}))
```
Browser (512px which is 2⁹):
<img width="997" alt="image" src="https://user-images.githubusercontent.com/33165467/162063853-5352fa3f-5ece-4171-9c4c-237c19911908.png">

## Example 2
Padding with 7px using `dripsy` `<View/>` with `sx`:

Code (7px):  
```tsx
import { View } from 'dripsy'
import { Title } from './styles'

const Button = ({ title }: { title: string }) => {
  return (
    <View
      sx={{
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#e03d26',
        borderRadius: 5,
        padding: 7,
      }}
    >
      <Title>{title}</Title>
    </View>
  )
}
```
Browser (256px wich is 2⁸)
<img width="989" alt="image" src="https://user-images.githubusercontent.com/33165467/162066254-6faea25e-1385-474e-951b-b5beab658faf.png">

## Example 3 - Works as Expected
Padding with 9px using `styled()`

Code(9px):
```ts
export const Container = styled(View)((_props) => ({
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: '#e03d26',
  borderRadius: 5,
  padding: 9
}))
```
Browser (9px):
<img width="990" alt="image" src="https://user-images.githubusercontent.com/33165467/162064633-4e0c1669-bc95-4456-9f97-6778038a491b.png">

**Comment by nandorojo** [comment]
what does your theme look like?

**Comment by nandorojo** [comment]
my guess is it’s pulling values from your `theme.space`, which would happen if you use a plain array.

**Comment by nandorojo** [comment]
I recommend doing this:

```ts
const theme = makeTheme({
  space: {
    $0: 0,
    $1: 4,
    $2: 8,
    $3: 16,
    $4: 32,
    $5: 64,
    $6: 128,
    $7: 256,
    $8: 512
  }
})
```

And then:

```tsx
<View sx={{ pr: '$3' }} />
```

**Comment by nandorojo** [comment]
Oof, I see the issue:

<img width="635" alt="Screen Shot 2022-04-06 at 5 16 47 PM" src="https://user-images.githubusercontent.com/13172299/162072416-c5edc232-8995-46ff-abde-e400aa765181.png">

Looks like we set the default `space` for you. So you can fix it with the comment above. I think this code is pulled over from `theme-ui`, and since everyone always overrides it, it's never been an issue until now.

It would be a breaking change to remove this, but I can do it in the next release. For now, if you explicitly set `space` in your theme, it will solve this.

**Comment by gabrielEloy** [comment]
@nandorojo thanks! passing the `space` property to `makeTheme` and using the theme's value in our components worked like a charm

**Comment by nandorojo** [comment]
awesome!
