### ISSUE TITLE
[types] Pressable: missing unstable_pressDelay

### ISSUE THREAD

**Issue by hirbod** [nandorojo/dripsy#195]
`Pressable` imported from dripsy does not support `unstable_pressDelay`

**Comment by nandorojo** [comment]
welcome to a PR

**Comment by hirbod** [comment]
I would love to, but have 0 clue. A quick look through the code did not shed any light for me where to find what I am looking for.

**Comment by nandorojo** [comment]
presumably it’s just the version of RN types? i assume this is a feature in a newer version?

**Comment by hirbod** [comment]
I am on 0.64.3 and the prop is working for me. (it is delaying my touch)
I can see that you pass Pressable through `styled` and the magic is happening here:
https://github.com/nandorojo/dripsy/blob/master/packages/core/src/css/styled.tsx

**Comment by nandorojo** [comment]
styled doesn’t edit any existing props. you’re probably on too old an RN types version?

**Comment by hirbod** [comment]
`    "@types/react-native": "~0.67.3",`

**Comment by nandorojo** [comment]
Dripsy doesn't create any types for components, it only forwards their existing ones. So if this isn't workin for you, I have to assume it's a problem with the types package you installed not having it
