### ISSUE TITLE
The linear gradient component crashes the app on expo SDK 45.

### ISSUE THREAD

**Issue by WillenOLeal** [nandorojo/dripsy#204]
# Steps to Reproduce: 

1. Create an expo managed app with expo init (SDK 45); 
2. Install `dripsy` and `@dripsy/gradient`(3.6.0); 
3. Use the gradient component anywhere on the app. 

#### Sample App.tsx 
``` typescript

import { Gradient } from "@dripsy/gradient";
import { DripsyProvider, makeTheme } from "dripsy";
import { StatusBar } from "expo-status-bar";
import { Text } from "react-native";

const theme = makeTheme({...});

export default function App() {
  return (
    <DripsyProvider theme={theme}>
      <Gradient
        colors={["green", "blue"]}
        sx={{ flex: 1, alignItems: "center", justifyContent: "center" }}
      >
        <Text>Open up App.tsx to start working on your app!</Text>
        <StatusBar style="auto" />
      </Gradient>
    </DripsyProvider>
  );
}

```
# Expected Result 

The app runs crash free

# Actual Result 

![Screen Shot 2022-05-08 at 8 50 58 PM](https://user-images.githubusercontent.com/54374330/167323406-7b73ab6f-4fbe-4e49-8fc5-f4e34fda70ad.png)

![Screen Shot 2022-05-08 at 9 04 38 PM](https://user-images.githubusercontent.com/54374330/167324166-e391d988-8f92-4e6b-9123-3b4cfec62ac6.png)

**Comment by nandorojo** [comment]
did you install expo-linear-gradient

**Comment by WillenOLeal** [comment]
@nandorojo yep! I have `"expo-linear-gradient": "~11.3.0",` installed. I also ran `expo start -c ` after it, but no luck.

**Comment by nandorojo** [comment]
does expo's normal gradient work for you?

**Comment by WillenOLeal** [comment]
Yes, the `expo-linear-gradient` works fine (code below). I noticed I am using  `expo-linear-gradient` version 11., however I think that the `@dripsy/gradient` package is using  version 10, could that be the reason? 

``` typescript

import { Gradient } from "@dripsy/gradient";
import { DripsyProvider, makeTheme } from "dripsy";
import { LinearGradient } from "expo-linear-gradient";
import { StatusBar } from "expo-status-bar";
import { Text } from "react-native";

const theme = makeTheme({
  
});

export default function App() {
  return (
    <DripsyProvider theme={theme}>
      <LinearGradient
        colors={["green", "blue"]}
        style={{ flex: 1, justifyContent: "center", alignItems: "center" }}
      >
        <Text>Open up App.tsx to start working on your app!</Text>
        <StatusBar style="auto" />
      </LinearGradient>
    </DripsyProvider>
  );
}

```

**Comment by nandorojo** [comment]
oh yeah that’s probably it. try a yarn resolution for now

**Comment by WillenOLeal** [comment]
Thank you! That did the trick! 

``` json
  "resolutions": {
    "@dripsy/gradient/**/expo-linear-gradient": "~11.3.0",
  },
```

**Comment by nandorojo** [comment]
I think just expo-linear-gradient should suffice, but that works too. I’ll make this a peer dep in a future release. Glad that worked!

**Comment by luizkc** [comment]
Even with the change mentioned above, I still can't get the gradient to show on iOS. I installed `@dripsy/gradient` on the `packages/app` directory. It works on web, but not on iOS, any clues?
<img width="1512" alt="Screen Shot 2022-06-18 at 1 37 12 AM" src="https://user-images.githubusercontent.com/44825405/174424558-d79d73ac-7afe-45ed-a607-32e33bada47d.png">

**Comment by nandorojo** [comment]
did you use the resolution above? i haven’t had time to focus on fixing this internally

**Comment by luizkc** [comment]
Yep, I did use the resolutions above.

**Comment by nandorojo** [comment]
are you using yarn?

**Comment by luizkc** [comment]
Yep. I'm using the Solito Starter Repo with Yarn. This is the package.json inside my `packages/app` directory:

```json
{
  "version": "0.0.0",
  "name": "app",
  "main": "index.ts",
  "dependencies": {
    "@dripsy/gradient": "^3.6.0",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "dripsy": "^3.6.0",
    "expo-linking": "^3.0.0",
    "firebase": "^9.8.3",
    "moti": "canary",
    "solito": "latest"
  },
  "resolutions": {
    "@dripsy/gradient/**/expo-linear-gradient": "~11.3.0"
  },
  "sideEffects": false
}
```

**Comment by nandorojo** [comment]
can you put the resolution in the root of the repo and then run yarn from the root?

**Comment by luizkc** [comment]
Tried moving the resolution to the root package.json and the gradient still won't render on iOS.

**Comment by nandorojo** [comment]
try `yarn why expo-linear-gradient`. does it work if you import direct from expo?

**Comment by nandorojo** [comment]
also try removing everything before `expo` in the resolution

**Comment by luizkc** [comment]
I removed everything before `expo` in the resolution. `yarn why expo-linear-gradient` ran successfully from the root dir. However, now the app won't build anymore. These are some of the errors it throws. Any other suggestions?

<img width="527" alt="Screen Shot 2022-06-18 at 11 15 59 AM" src="https://user-images.githubusercontent.com/44825405/174444888-8a13bb43-99d5-4d77-8bcc-7d998d152a9e.png">

**Comment by nandorojo** [comment]
what was the result of yarn why?

**Comment by nandorojo** [comment]
i see, if you’re using a custom dev client, the issue is that expo isn’t autolinking to the right place. so you should also add install expo-linear-gradient in apps/expo

the solito starter also isn’t on SDK 45 (yet), so you need your yarn resolution to match the sdk version you’re on. deoendencies are always the issue…lol

**Comment by luizkc** [comment]
Yarn why results:

<img width="507" alt="Screen Shot 2022-06-18 at 11 30 28 AM" src="https://user-images.githubusercontent.com/44825405/174445487-ee045fda-0f6b-4784-a76c-e52359ab42f6.png">
 
 So if I install it in the expo directory, should I also leave it installed in the packages/app directory for next.js to be able to use it as well?

**Comment by nandorojo** [comment]
that’s correct

**Comment by luizkc** [comment]
I did the below and I'm still not seeing the gradient. Let me know if I did anything wrong or if there's anything else I can try. Thank you for being so helpful!

- `expo-linear-gradient` with version 11.0.3 is installed in `packages/app` and `apps/expo`
- a resolution like the below, targeting `expo-linear-gradient` with the same version is in the `package.json` in the root. I tried both ways:
```jsonc
// suggestion 1: app builds but no gradient
  "resolutions": {
    "@dripsy/gradient/**/expo-linear-gradient": "~11.3.0"
  },

// suggestion 2: app doesn't build, see the last error message I posted
  "resolutions": {
    "expo-linear-gradient": "~11.3.0"
  },
  ```

**Comment by luizkc** [comment]
So this is the solution I've gone with for now:
- Created a Gradient component
- `Gradient/index.web.tsx` uses `@dripsy/gradient`
- `Gradient/index.tsx` uses `expo-linear-gradient`
- I can't use my `<Gradient />` component anywhere in the `packages/app/provider` directory
- I can use my `<Gradient />` component in almost any other directory and it will render fine on iOS and the web

**Comment by nandorojo** [comment]
Can you try upgrading to `3.7.x` for both dripsy and the gradient?
