### ISSUE TITLE
Any ideas about getting Dripsy variants and styles in Auto-complete on Webstorm/VS Code?

### ISSUE THREAD

**Issue by thegitparticle** [nandorojo/dripsy#208]

**Comment by nandorojo** [comment]
it works in vs code if you follow the docs

**Comment by thegitparticle** [comment]
I did the setup, the styles work fine but the auto complete suggestions do not appear on VS Code. Is there some extra steps needed for this?

**Comment by nandorojo** [comment]
and you have typescript installed with a tsconfig file?

**Comment by thegitparticle** [comment]
yes
