### ISSUE TITLE
react navigation header style is broken 

### ISSUE THREAD

**Issue by mokuzuu** [nandorojo/dripsy#218]
# Description
I use react-navigation and dripsy with following version
```json
"@react-navigation/native": "^6.0.10",
"@react-navigation/native-stack": "^6.6.2",
"dripsy": "^3.6.0",
```
When I use dripsy View as Stack screen component props
```tsx
import {View} from 'dripsy'
...
<Stack.Screen name="TopicsList" component={() => <View />} />
```
and it puts header at the bottom screen as screenshot.
<img width="400" alt="スクリーンショット 2022-07-17 午前0 04 27" src="https://user-images.githubusercontent.com/41939914/179358173-fc823dde-0428-41cd-a5da-7f540ddf0959.png">

It looks like `flex-direction` property, which supposed to be `column-reverse` is overridden by another class and sets `flex-direction: column`
<img width="657" alt="スクリーンショット 2022-07-17 午前0 05 35" src="https://user-images.githubusercontent.com/41939914/179358223-2c1c206e-8196-4fcf-a28f-9ec2d88884d3.png">

When I disable `flex-direction: column` and it (pretty much) fix the style.
<img width="1425" alt="スクリーンショット 2022-07-17 午前0 08 40" src="https://user-images.githubusercontent.com/41939914/179358301-ec966e95-ea6b-45d4-99eb-f873637c6beb.png">

This issue won't happen when I use `react-native` View component

**Comment by nandorojo** [comment]
I'm not really sure what the gist of the issue is. Can you please make a reproduction at https://snack.expo.io and show expected / actual behavior?

**Comment by mokuzuu** [comment]
Thank you for response. I tried to reproduce the bug on expo snack but I couldn't...
I made a repo which I could reproduce bug on my mac book pro
https://github.com/mokuzuu/dripsy-react-navigation-issue-218/

**Comment by mokuzuu** [comment]
This is [expo snack link](https://snack.expo.dev/D8Tv2cKCS) which works as expected (header is displayed at the top of the screen).

**Comment by nandorojo** [comment]
i think native stack is kind of messed on web in general, maybe try normal stack on web?

https://github.com/showtime-xyz/showtime-frontend/blob/911795b8a0f0a48d8fda592bb9e1b818e4cc1559/packages/app/navigation/create-stack-navigator.web.tsx

**Comment by mokuzuu** [comment]
You are right! It fixes the issue! I have another UI issue with drawer, but it might be fixed with same approach. I will try later.

I feel this is beneficial to some people. May I update README to note about this?

**Comment by mokuzuu** [comment]
Thank you very much Fernando
