### ISSUE TITLE
shorthand styles do not override longhand

### ISSUE THREAD

**Issue by jjenzz** [nandorojo/dripsy#223]
in both of these examples the padding will be `30`:

```jsx
const Button = styled(Pressable)({
  backgroundColor: 'red',
  px: 30,
  py: 30,
  p: 10,
});
```

```jsx
const Button = styled(Pressable)({
  backgroundColor: 'red',
  px: 30,
  py: 30,
});

return (
  <Button sx={{ p: 10 }}>
    <Text>Button</Text>
  </Button>
);
```

i had expected styles that are assigned last would override. is this a misplaced expectation or a bug?

**Comment by nandorojo** [comment]
this is how react native styling works. specificity takes precedent over key placement.

**Comment by nandorojo** [comment]
`paddingTop` will always override `padding`, regardless of the order in which it’s written

**Comment by nandorojo** [comment]
going to close this one since the behavior is as expected

see: https://github.com/necolas/react-native-web/issues/40#issuecomment-151685237

**Comment by jjenzz** [comment]
ahhh interesting, okay, my bad 🙈  thanks for taking the time to look regardless
