### ISSUE TITLE
Allow custom components w/ multiple style props to accept sx styles

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/dripsy#23]
It's common for custom components to receive multiple style props.

```jsx
<Chat 
  bubbleStyle={{ bg: 'primary' }}
  textStyle={{ color: 'text' }}
/>
```

It would be nice to have an API that lets these custom components take advantage of the `sx` prop.

### Option 1: `sx` hook.

One option is to just expose the `sx` via a hook, which has been discussed on #12 (I believe). It'd just be a connected `css` function.

```jsx
const sx = useSx()

<Chat 
  bubbleStyle={sx({ bg: ['primary', 'secondary'] })}
  textStyle={sx({ color: 'text' })}
/>
```

Unfortunately, it looks like this would break the implementation of Fresnel on web, unless we had some serious magic going on with a custom pragma. I think the behavior would just get confusing if the pragma is required with a hook.

### Option 2: `createThemedComponent` 

I haven't thought through what it would actually look like, but maybe `createThemedComponent` could receive an array of prop keys that should also receive `sx` styles.

```jsx
const ThemedChat = createThemedComponent(Chat, {
  sxProps: ['bubbleStyle', 'textStyle'] // keyof ComponentProps<typeof Chat>
})

...
<ThemedChat 
  bubbleStyle={{ bg: 'primary' }}
  textStyle={{ color: 'text' }}
/>
```

Is there a way we could edit the props on TypeScript such that you still get typed suggestions for `bubbleStyle` and `textStyle`? I'm sure there's a way...

---

I wanted to write down my thoughts before forgetting.

**Comment by cmaycumber** [comment]
Can we add both options here or do you think we need to pick one over the other?

If I had to pick one it'd probably be the hook because it's more react-ish/standard in a sense in my opinion.

**Comment by nandorojo** [comment]
I probably would too, unfortunately I don't know how it would work with fresnel. We're no longer just passing a style object, but also wrapping the component itself with the fresnel solution and creating parent dom nodes.

**Comment by nandorojo** [comment]
This could be possible now with v2.

**Comment by nandorojo** [comment]
`useSx` prop added in `v2.2.0`. And that's the final issue closed.
