### ISSUE TITLE
@expo/html-elements@0.0.1" has incorrect peer dependency "react-native-web@~0.13.7

### ISSUE THREAD

**Issue by SkySails** [nandorojo/dripsy#233]
Hi! 👋 Firstly, thanks for your work on this project! 🙂

When using this package in a project together with `react-native-web@0.18.7`, I get this peer dependency warning:

```cmd
warning "dripsy > @dripsy/core > @expo/html-elements@0.0.1" has incorrect peer dependency "react-native-web@~0.13.7"
```

Looking further into this, it looks like more recent versions of `@expo/html-elements` no longer has any peer dependencies. I tried modifying the dependencies for dripsy to use an up-to-date version and the warning went away:

```diff
diff --git a/node_modules/@dripsy/core/package.json b/node_modules/@dripsy/core/package.json
index aae8edb..96305fd 100644
--- a/node_modules/@dripsy/core/package.json
+++ b/node_modules/@dripsy/core/package.json
@@ -80,7 +80,7 @@
     "typescript": "^4.4.3"
   },
   "dependencies": {
-    "@expo/html-elements": "^0.0.1",
+    "@expo/html-elements": "^0.2.0",
     "@react-native-community/hooks": "^2.6.0",
     "@theme-ui/css": "^0.4.0-rc.1",
     "stable-hash": "^0.0.2",
```

I could act like the beloved dependabot by making this change and running the linter/tests and creating a PR, but when I tried doing so there were lots of linting issues before making any edits. This, combined with the test coverage, means that I don't feel comfortable judging if this change would break anything.

It seems to work just fine for my use case, but I would really appreciate at least a second pair of eyes on this 😄

**Comment by nandorojo** [comment]
Can you try upgrading to `3.7.x` for both dripsy and the gradient?

**Comment by SkySails** [comment]
Looks good, thank you! 🙌
