### ISSUE TITLE
Wrong typescript autocomplete

### ISSUE THREAD

**Issue by paulrostorp** [nandorojo/dripsy#240]
Autocomplete suggests any value from the theme for React Native style properties... I've tested a few different theme configurations, but this behaviour is consistent

![Screenshot 2022-09-28 at 10 59 16](https://user-images.githubusercontent.com/1866649/192737595-b1becd05-81c6-4e5d-b5dc-1d8ae750e572.png)
![Screenshot 2022-09-28 at 10 59 41](https://user-images.githubusercontent.com/1866649/192737601-aba44c17-916a-4074-ab60-06a3474059e0.png)

cc: @nandorojo

**Comment by nandorojo** [comment]
closing as duplicate
