### ISSUE TITLE
react native web dripsy create StyleSheet rules

### ISSUE THREAD

**Issue by chrisarts** [nandorojo/dripsy#248]
Im experimenting this issue IDK if is related to dripsy or react native web:
![Screen Shot 2022-11-16 at 5 06 50 PM](https://user-images.githubusercontent.com/3628422/202304877-cc0a24f2-fcca-4c09-a1ed-e8bdad560051.png)

**Comment by nandorojo** [comment]
that’s RNW code, not dripsy
