### ISSUE TITLE
Mocking dripsy?

### ISSUE THREAD

**Issue by wezter96** [nandorojo/dripsy#252]
Do you have any suggestions on what should be done regarding mocking and such with dripsy in unit tests?

I have tests that seem to fail because of theme not being defined and if I mocked that then I got the same issues regarding styled.
 TypeError: Cannot read properties of null (reading 'theme') and if I mock my theme I get:
  TypeError: (0 , _dripsy.styled)(...) is not a function
 
![image](https://user-images.githubusercontent.com/23472050/203801836-631c9696-0ca2-43e1-ab00-5572306ae943.png)
![image](https://user-images.githubusercontent.com/23472050/203801919-62ecef77-8b3b-4f60-8f26-6b073b046ba0.png)

**Comment by ryee-dev** [comment]
Also having this issue 😢

**Comment by nandorojo** [comment]
That error indicates that the provider isn’t present above in the component tree…

**Comment by jcamden** [comment]
@nandorojo , you rock. With your comment, it took me all of 30 seconds to figure it out and create a decorator to wrap my Storybook stories with the Dripsy component. Hot reloaded and that was that. 

For the jest issue above, I think you'd pretty much want the same thing. Probably something like,
```
const renderWithDripsy = (component) => render(<Dripsy>{component}</Dripsy>)
```

**Comment by ryee-dev** [comment]
@nandorojo Woooo I feel dumb haha thanks!

**Comment by nandorojo** [comment]
🤝
