### ISSUE TITLE
Can't resolve '@theme-ui/css/dist/types' in '...node_modules/@theme-ui/core/dist'

### ISSUE THREAD

**Issue by eddyhdzg** [nandorojo/dripsy#26]
Library currently not working

` web  Failed to compile.
/Users/eddyhdzg/Desktop/my-react-app/node_modules/@theme-ui/core/dist/index.esm.js
Module not found: Can't resolve '@theme-ui/css/dist/types' in '/Users/eddyhdzg/Desktop/my-react-app/node_modules/@theme-ui/core/dist'`

**Comment by nandorojo** [comment]
Odd. Could you share your package.json / a minimal repo?

**Comment by eddyhdzg** [comment]
```
{
  "dependencies": {
    "dripsy": "^0.5.2",
    "expo": "~38.0.0",
    "next": "9.3.5",
    "next-compose-plugins": "^2.2.0",
    "next-transpile-modules": "^4.1.0",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-web": "0.11.7"
  },
  "devDependencies": {
    "@babel/core": "7.9.0",
    "@expo/next-adapter": "2.1.0"
  },
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo web",
    "eject": "expo eject"
  },
  "private": true
}
```


### Steps to recreate

- 1 Init Expo + Next.js

```npx create-react-native-app -t with-nextjs```
- 2 Add dripsy

```npm i dripsy```
- 3 Add  next-compose-plugins next-transpile-modules

```npm i next-compose-plugins next-transpile-modules```

- 4 next.config.js
```
const withPlugins = require('next-compose-plugins');
const withTM = require('next-transpile-modules')([
  'dripsy',
  // you can add other packages here that need transpiling
]);

const { withExpo } = require('@expo/next-adapter');

module.exports = withPlugins(
  [withTM],
  withExpo({
    projectRoot: __dirname,
  })
);
```
- 6 edit pages/index.js

```
// @generated: @expo/next-adapter@2.1.0
import React from "react";
import { StyleSheet, Text, View } from "react-native";
import { ThemeProvider } from "dripsy";

const theme = {
  colors: {
    text: "#000",
    background: "#fff",
    primary: "tomato",
  },
  fonts: {
    body: "system-ui, sans-serif",
    heading: '"Avenir Next", sans-serif',
  },
  spacing: [10, 12, 14],
};

export default function App() {
  return (
    <ThemeProvider theme={theme} options={{ ssr: true }}>
      <View style={styles.container}>
        <Text style={styles.text}>Welcome to Expo + Next.js 👋</Text>
      </View>
    </ThemeProvider>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  text: {
    fontSize: 16,
  },
});

```

- 6 run web

```npm run web```

**Comment by nandorojo** [comment]
Looks like this is an issue with theme ui. I got the same error in an empty theme ui project without Dripsy. I'll see if I can find more.

**Comment by rafaelrinaldi** [comment]
Is `resolutions` a Yarn-only feature? Can't seem to find a way to do it in `npm`.

**Comment by nandorojo** [comment]
I haven't used npm in a while, but maybe this will help? https://github.com/rogeriochaves/npm-force-resolutions

**Comment by rafaelrinaldi** [comment]
@nandorojo Yup, that's what I found. Just wanted to make sure I wasn't missing anything. Thanks 👍

**Comment by eddyhdzg** [comment]
It worked with the https://github.com/rogeriochaves/npm-force-resolutions!

**Comment by nandorojo** [comment]
Just checking in here, has anyone gotten this to work without using `yarn resolutions`? I'm looking to upgrade theme-ui, and want to see if anyone is using a newer version.

The previous solution was to add this to your package.json:

```json
{
  "resolutions": {
    "@theme-ui/core": "0.4.0-rc.1",
    "@theme-ui/css": "0.4.0-rc.1",
    "@theme-ui/mdx": "0.4.0-rc.1"
  }
}
```

Do you guys still have this in your code?
