### ISSUE TITLE
Define custom shorthands / aliases

### ISSUE THREAD

**Issue by jaivinwylde** [nandorojo/dripsy#261]
Are there any plans to allow for defining custom shorthands (aliases)?

What would need to be added to get this to work? I'm not familiar with the codebase, but I could try making a PR.

**Comment by nandorojo** [comment]
The only issue is that the Dripsy internals are a bit of a mess but I do think this is a good idea.

**Comment by jaivinwylde** [comment]
What do you think about adding tamagui's shorthands to the alias variable in the meantime? They have a lot of sane defaults that cover almost all of the styles that people often use.

**Comment by nandorojo** [comment]
if you point me to the file i can do that

**Comment by nandorojo** [comment]
but ideally i’d accept a PR

**Comment by jaivinwylde** [comment]
on it

**Comment by jaivinwylde** [comment]
I added tamagui's shorthands, but I think it makes sense to keep this issue open since the custom shorthands feature hasn't been added yet

**Comment by nandorojo** [comment]
`theme.aliases` implemented in v4.
