### ISSUE TITLE
Heading elements rendering to the same H1 tag

### ISSUE THREAD

**Issue by jeffscottward** [nandorojo/dripsy#262]
Regardless of which element I chose - ultimately the tag will be H1 (even if there is differently applied CSS I assume)
<img width="467" alt="Screenshot 2022-12-12 at 6 08 14 PM" src="https://user-images.githubusercontent.com/1263486/207176833-74ee5fda-9647-4f3e-8473-d27ff200798a.png">
<img width="626" alt="Screenshot 2022-12-12 at 6 08 40 PM" src="https://user-images.githubusercontent.com/1263486/207176938-6b7d0412-a94e-4e56-98a9-7fefe5a16caf.png">

**Comment by nandorojo** [comment]
hm, this would likely be an issue with `@expo/html-elements `

**Comment by jeffscottward** [comment]
Just merged https://github.com/expo/expo/issues/20458

**Comment by jeffscottward** [comment]
Can we get this updated?

**Comment by nandorojo** [comment]
Which expo html elements version is it? I believe Dripsy is already on the latest one. I republished `3.10` though.
