### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by yepes** [nandorojo/dripsy#274]
Hi,

Just trying out dripsy doing some research about which library to use for styling. Dripsy seems to check all my points. Looking at the example on the docs, the intellisense seems like a big selling point. The thing is I tried to install dripsy on an expo project and also created a blank one (with solito and all the stuff) with npx create-solito-app@latest my-dripsy-app but intellisense doesn't seem to work at all. For example, in the app with the create-solito-app command, if i go to:
packages/app/features/home/screen.tsx

![image](https://user-images.githubusercontent.com/1114453/224174857-3991f955-58af-4450-a0cb-5729e4be5943.png)

Also tried to:
```
 types: {
    reactNativeTypesOnly: true // default false
  }
```

with no difference. Tried with intellij (phpstorm) and also with vsc. Am I missing something?

**Comment by nandorojo** [comment]
yeah the intellisense stuff has been really difficult to adapt to newer versions of RN / TypeScript. i want to get it fixed up, but I just don’t have the time to dedicate to it right now

**Comment by yepes** [comment]
I've been taking a look at the source code but the ts types definitions are just too much for my knowledge. As a curios thing, intellisense does not work on intellij (phpstorm) but when i assign a wrong value, the linter complais. Well, is better than nothing.

**Comment by nandorojo** [comment]
Here's a new umbrella issue for this: https://github.com/nandorojo/dripsy/issues/276
