### ISSUE TITLE
Fatal error on app launch in 4.1.0

### ISSUE THREAD

**Issue by thecoorum** [nandorojo/dripsy#288]
Recently I upgraded package version from 3.6.0 to 4.1.0 and while launching the app I see the error `Unexpected keyword 'const' (248:26)` which seems to be internal as my project doesn't use TS. Stacktrace outputs that the error is in `makeTheme` exported method. Downgrading back to 3.6.0 eliminates the issue

## Media
<img width="555" alt="image" src="https://github.com/nandorojo/dripsy/assets/32096016/47314447-52f7-4a7c-89c7-58c0cd9bf9cb">

**Comment by thecoorum** [comment]
Just curious why it was working with 3.6.0 without TS 🤔

**Comment by nandorojo** [comment]
So...pretty much, `const` is a TS 5.0 feature. RN uses source files to run the code. Since the TS source files are using a new version, it's not working with your current RN setup. Your previous setup likely worked anyway, because your Babel config was just transpiling away the TS 4.0 code

**Comment by nandorojo** [comment]
@thecoorum could you try upgrading to `4.3.4` and see if this error goes away?

**Comment by thecoorum** [comment]
@nandorojo while trying to install `4.3.4` it says that this version is not released yet. The latest listed is `4.3.3`

**Comment by nandorojo** [comment]
oh, maybe the publish script failed. i'll try again today

**Comment by thecoorum** [comment]
@nandorojo just checking in 'cause still no `4.3.4` on npm

**Comment by nandorojo** [comment]
does the latest version fix it? if not i'll republish today

**Comment by thecoorum** [comment]
Yeah, it seems to be working with 4.3.3
