### ISSUE TITLE
Wrong type for `variant` on `TextInput`

### ISSUE THREAD

**Issue by paulrostorp** [nandorojo/dripsy#292]
With ts@5.0.4 and dripsy `4.3.3` I get the following error when using `variant` on a dripsy `TextInput`:
![Screenshot 2023-06-01 at 10 38 30](https://github.com/nandorojo/dripsy/assets/1866649/03cbf623-7594-49cd-8d53-70b860eadb66)

I can force the expected `undefined` type by doing the following
```js
variant={"text.title3Emphasis" as unknown as undefined}
```

**Comment by paulrostorp** [comment]
it seems like `strictVariants: false` has no effect

**Comment by nandorojo** [comment]
I think inputs have their own variants under `theme.inputs` that’s why.

**Comment by nandorojo** [comment]
did you try using `theme.inputs`?
