### ISSUE TITLE
Will this also work across mobile and web projects?

### ISSUE THREAD

**Issue by cmaycumber** [nandorojo/dripsy#3]
Will the library work with both rnw and normal react-native? Would love to get a project going that has a bunch of code reuse and this seems like the way to go. Thanks for creating this, I was looking for a similar solution for a while with no avail. 

On a side note would love to help work on the library if you need any.

**Comment by nandorojo** [comment]
Yes! If you check out my github profile, you’ll see that a lot of my open source work is dedicated towards making react native + react native web / expo web all work nicely together with one API.

This library is meant to bring together normal react native with react native web for all things styles :)

**Comment by cmaycumber** [comment]
Sweet I'll take a look thanks for the quick response!
