### ISSUE TITLE
[bug] Style value conflicts with alias

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/dripsy#30]
What do we do if the style value we want to pass conflicts with the key for one of our aliases?

```js
const theme = {
  space: [0, 4, 8, 16, 32, 64, 128, 256, 512]
}
```

If we have the above theme, then calling `space[1] = 4`, and `space[6] = 128`.

## **Situation 1:**

Let's say I didn't want to use the `128` value, but instead, I just wanted to pass padding of `6` pixels.

```tsx
<View
  sx={{
    padding: 6 // returns 128
  }}
/>
```

So, how do I get 6 in there?

The answer: I could just pass the correct value to `style` instead of `sx`. However, `style` currently is treated as an `sx` prop. Since this doesn't make much sense, I should get rid of [this](https://github.com/nandorojo/dripsy/blob/0aeb6e3db34236ae59a5d3acec474f7e0a118039/src/css/index.tsx#L389) line and just use the raw style object.

```tsx
<View
  style={{
    padding: 6 // returns 128, should return 6 after refactor
  }}
/>
```

## **Situation 2:**

While that solves situation 1, what if I want to use theme values to calculate `6px`?

In my case, I want to grab `space[1]` (i.e. `4px`), and multiply it by 1.5 to get `6px`.

```tsx
<View
  sx={{
    // this is 4 * 1.5 = 6
    // but wait, it gives 128, from the theme!
    padding: (theme) => theme.space[1] * 1.5
  }}
/>
```

Alright, so once again, I end up with `128px`, not `6px`.

To borrow from **situation 1**:

```tsx
const { theme } = useThemeUI()

<View
  style={{
    padding: theme.space[1] * 1.5 // this would solve it after the refactor of changing sx -> style
  }}
/>
```

Hmm...there's still one edge case, though. What if I wanted to use that value in a responsive array?

```tsx
const { theme } = useThemeUI()
<View
  sx={{
    padding: [theme.space[1] * 1.5, theme.space[2] * 1.5]
  }}
/>
```

In this case, the only way to use responsive arrays is via the `sx` prop. But if I use the `sx` prop, I am stuck with theme values, and can't use the `6px` work-around from web.

## What does theme-ui do?

This problem is easily solved in `theme-ui`. You can just pass a raw `'6px'` string, and boom, you're done.

But React Native doesn't allow `'6px'`, because it only uses numbers.

## Solution

Could we edit the `css` function to check for `<number>px` values, and turn these into numbers to avoid making RN angry?

If so, then this would work:

```tsx 
<View
  sx={{
    padding: theme => [`${theme.space[1] * 1.5}px`, `${theme.space[2] * 1.5}px`]
  }}
/>
```

**Comment by nandorojo** [comment]
Current workaround:

```tsx
<View
  sx={{
    padding: 6 - .00000001
  }}
/>
```

😅

**Comment by cmaycumber** [comment]
In my experience, I usually use an object for space object inside of them so that I can access the values with a specified key. I know this wouldn't work for everyone. 

Maybe a potential solution would be adding the ability to pass a number as a string and use that as an override. For example, if you passed '6' it would detect if parseInt('6') is Nan or not and then use that. I think that would give you the same effect as '6px'.

One downside to this would be if someone was using an object with key '6' but in that case, we could just apply the reverse logic and potentially use the number 6 to add the values by detecting if they are using an array vs object.

**Comment by nandorojo** [comment]
Yeah, it's a bit tricky at the moment...I'm sticking with the annoying workaround for now. It's pretty uncommon to run into this, and I like using the array syntax, so I'll close for the time being.

**Comment by nandorojo** [comment]
Thought of a solution. Allow `16px` values, and in the `css` function, check if a value is a string that `endsWith(px)`, and if so, make it a raw number that avoids an alias.

**Comment by jenniferpham** [comment]
@nandorojo - I was looking at docs from other libraries, and I think this is a very user-friendly way for devs to code hard-coded raw CSS values vs indices of the theme key.
https://github.com/sammdec/theme-ui-native#raw-values

Do you forsee any issues if a developer uses a number type for indices and a string that can be parsed to a number for raw CSS values? 

```
import { Text } from "react-native"

export default props => (
  <Text
    sx={{
      marginY: "2", // uses the raw value `2`
      marginX: 2 // picks up value from `theme.space[2]`
    }}
  >
    Hello
  </Text>
)
```

**Comment by nandorojo** [comment]
This will be solved by not theming the `style` prop in an upcoming version.

**Comment by nandorojo** [comment]
`style` is no longer themed in `v2.1.0`, so you can use that. If you need it responsive, you can use `useResponsiveValue`.
