### ISSUE TITLE
how to run with jest

### ISSUE THREAD

**Issue by jsellam** [nandorojo/dripsy#301]
Hi, 
I'm starting a new project with react-native (BARE) 0.72.6
I have added dripsy with typescript and all is working well on devices and simulator, but my tests with jest are not working.

I use @testing-library/jest-native/extend-expec
and when I run "jest --no-cache" I have this error : 

```
   /Users/jeremie/Documents/PROJETS/Metyis/kedrion/packages/front/mobile/node_modules/dripsy/build/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from './core';
```
<img width="649" alt="Capture d’écran 2023-12-18 à 13 59 40" src="https://github.com/nandorojo/dripsy/assets/26770991/ebfe870a-0117-4533-b543-7dc415ebb944">

Do you know how to use dripsy with jest please ?

thx
Jeremie.

**Comment by nandorojo** [comment]
Honestly not totally sure, I haven’t used jest much before besides simple functions.

**Comment by jsellam** [comment]
I have the answer, I have added this in jest.config.js

```
**const libsThatRequiredCompilation = ['dripsy', '@expo/html-elements'].join('|');**

module.exports = {
  preset: 'react-native',
  setupFilesAfterEnv: ['@testing-library/jest-native/extend-expect'],
  **transformIgnorePatterns: [
    `node_modules/(?!((jest-)?react-native|${libsThatRequiredCompilation}|@react-native(-community)?)/)`,
  ],**
};
```
