### ISSUE TITLE
[Typescript] how to type a strict color value ?

### ISSUE THREAD

**Issue by jsellam** [nandorojo/dripsy#302]
Hi, I'm using a config in a ts file with colors, but I would like to type the color field as strict dripsy color

<img width="447" alt="Capture d’écran 2023-12-28 à 12 39 20" src="https://github.com/nandorojo/dripsy/assets/26770991/33e8ab44-745e-4afd-b800-0bc0bcf663d2">

Actually I don't know how to type my color field, I use string, and I have an error in my sx prop 👍 
<img width="493" alt="Capture d’écran 2023-12-28 à 12 39 51" src="https://github.com/nandorojo/dripsy/assets/26770991/b5af8d06-594b-4a0d-a03e-9794d58a3737">

Who know what type to use please ?

Thx,
Jeremie.

**Comment by jsellam** [comment]
Ok I have the answer : 

`type Color = keyof ReturnType<typeof useDripsyTheme>['theme']['colors'];`

**Comment by nandorojo** [comment]
Yes, or you can simply import `Theme` from dripsy
