### ISSUE TITLE
autocomplete not working

### ISSUE THREAD

**Issue by emdile** [nandorojo/dripsy#305]
I don't get autocomplete with typescript.

typescript 5.1.6
expo 50.0.6
dripsy 4.3.4

config for dripsy
![Screenshot 2024-02-19 130752](https://github.com/nandorojo/dripsy/assets/100505981/23655994-d1db-46a0-a960-2be5fe9b0579)

No autocomplete with theme type
![Screenshot 2024-02-19 130724](https://github.com/nandorojo/dripsy/assets/100505981/74717e88-c8fb-4886-a0a7-167c4fef3518)

**Comment by nandorojo** [comment]
Does commenting out any of the fields help? #297 seems related

**Comment by nandorojo** [comment]
Please share your full theme

**Comment by Elie-A-98** [comment]
Can you share where do you expect to get autocomplete ? With a commit of what you expect ?

**Comment by emdile** [comment]
> Can you share where do you expect to get autocomplete ? With a comment of what you expect ?

```
import { shadow } from '@/contants/theme';
import { LabelInput } from '@/design/input';
import { Col, Row } from '@/design/layout';
import { Button } from '@/design/touchable';
import { H4 } from '@/design/typography';
import { SxProp, TextInput } from 'dripsy';
import { Modal } from 'react-native';

type AddFolderModalProps = {
	disabled?: boolean;
	visible: boolean;
	loading?: boolean;
	onClose: () => void;
	validate: () => void;
	handleOnChange: (t: string, field: string) => void;
};

export const AddFolderModal = ({
	disabled,
	validate,
	visible,
	onClose,
	handleOnChange,
}: AddFolderModalProps) => {
	return (
		<Modal
			animationType="fade"
			transparent={true}
			visible={visible}
			onRequestClose={() => {
				onClose();
			}}
		>
			<Col
				sx={{
					flex: 1,
					justifyContent: 'center',
					alignItems: 'center',
				}}
				style={{ backgroundColor: '#00000011' }}
			>
				<Col
					sx={{
						backgroundColor: 'white',
						padding: 16,
						boxShadow: 'md',
						// ...(shadow.dark as any),
					}}
					// style={[shadow.dark]}
				>
					<H4>Ajout de dossier</H4>
					<LabelInput
						label="Nom dossier"
						onChangeText={(t) => handleOnChange(t, 'name')}
					/>
					<Row
						sx={{
							rowGap: 8,
							justifyContent: 'flex-end',
						}}
					>
						<TextInput sx={{dis}} >Trdfdf</TextInput>
						<Button
							title="Annuler"
							containerStyle={{ bg: '$background', color: '$black', mr: '$2' }}
							onPress={onClose}
						/>
						<Button
							title="Sauvegarder"
							disabled={disabled}
							onPress={validate}
						/>
					</Row>
				</Col>
			</Col>
		</Modal>
	);
};
```

my components have props of type SxProp, but no autocomplete

I tried TextInput component form dripsy, same thing

![Screenshot 2024-02-19 140908](https://github.com/nandorojo/dripsy/assets/100505981/225431a3-d231-483a-90cd-daf70fd596ae)

**Comment by nandorojo** [comment]
Do you have `@types/react-native` installed? It shouldn't be installed. Try

```sh
yarn why @types/react-native
```

**Comment by Elie-A-98** [comment]
Also make sure to restart ts language server after you do the interface merging

**Comment by nandorojo** [comment]
Can you also try installing `dripsy@4.3.5`

**Comment by emdile** [comment]
> Do you have `@types/react-native` installed? It shouldn't be installed. Try
> 
> ```shell
> yarn why @types/react-native
> ```

```
yarn why @types/react-native
yarn why v1.22.5
[1/4] Why do we have the module "@types/react-native"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@types/react-native@0.73.0"
info Has been hoisted to "@types/react-native"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "20KB"
info Disk size with unique dependencies: "75.79MB"
info Disk size with transitive dependencies: "212.65MB"
info Number of shared dependencies: 216
Done in 3.00s.
```

**Comment by emdile** [comment]
> Can you also try installing `dripsy@4.3.5`

No change

**Comment by emdile** [comment]
> Also make sure to restart ts language server after you do the interface merging

I did that

**Comment by Elie-A-98** [comment]
Try removing @types/react-native and restart ts languagr server again. Basiclly don't let ts use the types from @types/react-native

**Comment by emdile** [comment]
> Try removing @types/react-native and restart ts languagr server again. Basiclly don't let ts use the types from @types/react-native

No change. I don't understand. In my solito project it is work with: 
dripsy 4.3.3
typscript 5.1.3

but in simple expo project with same config it is not work.

**Comment by Elie-A-98** [comment]
I tried it with an expo project as well, and it works fine for me. Can you publish a minimal reproducable example ?

**Comment by emdile** [comment]
I decided to create a new expo project, I installed dripsy and created the theme it worked. Then I copied the code from the old project and everything works. I do not know why.

Thank you for the time you gave me.
