### ISSUE TITLE
Web Container Styled being applied to all fresnel divs when using responsive values

### ISSUE THREAD

**Issue by cmaycumber** [nandorojo/dripsy#36]
## Description

When using the dripsy fresnel-2 branch the webContainerSx prop is applying styles to all fresnel divs, not just the current breakpoint when multiple fresnel divs a present.

## Example

Component:
```jsx
<Container
      webContainerSx={{ flex: 1 }}
      sx={{ justifyContent: "center", alignItems: "center", flex: 1 }}
    >
    <Text>Here</Text>
</Container>
```

Theme value: 
```jsx
container: {
  px: ["base", "large", "huge"],
},
```

**Comment by nandorojo** [comment]
Since this prop is an `sx` prop that applies to HTML, you can treat it as such and use responsive arrays directly in it. However, if you don't pass any arrays to `sx`, it doesn't do anything. 

If you want to apply different styles per breakpoint to `webContainerSx`, you can do so with by using arrays within it. Does that make sense?

I might have misinterpreted what you mean here, so let me know if I did. It seems like you need to apply the container styles to the `webContainerSx` (width: 100%, maxWidth: X, etc.)

**Comment by nandorojo** [comment]
If you pass `webContainerSx={{ flex: [1, 0] }}`, then it should work by breakpoint, does it?

**Comment by cmaycumber** [comment]
Here's a decent screenshot that shows what I'm seeing:
<img width="1274" alt="Screen Shot 2020-09-23 at 7 32 53 PM" src="https://user-images.githubusercontent.com/36460656/94084484-a5371a00-fdd3-11ea-8d95-ee2094d64404.png">

So for the 5 fresnel breakpoints, each gets a flex value of 1 which creates 5 rows of divs but only the current breakpoint renders the children.

When trying the array syntax I just get the same thing just the larger breakpoints don't flex at all.

**Comment by nandorojo** [comment]
Can you see if this fixes it? https://github.com/nandorojo/dripsy/commit/93837387eae9062f5f339ad40776c17cbbd6346f

It's published to `1.0.1`, I'll try it myself too.

**Comment by cmaycumber** [comment]
> Ah, I suppose the style should only apply to the active div, right?

Yeah exactly.

> Can you see if this fixes it? [9383738](https://github.com/nandorojo/dripsy/commit/93837387eae9062f5f339ad40776c17cbbd6346f)
> 
> It's published to `1.0.1`, I'll try it myself too.

Will do.

**Comment by cmaycumber** [comment]
Looks like that push fixed it on my end!

**Comment by nandorojo** [comment]
This fixed some style issues on my app, good catch, I didn't even realize that was causing it.

**Comment by nandorojo** [comment]
Let me know if this resurfaces, closing for now.
