### ISSUE TITLE
Tree shaking

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/dripsy#41]
Using next's webpack analyzer, I noticed that all of RNW is getting imported into every one of my pages. I still need to investigate this further, but I wonder if dripsy is contributing to RNW's tree shaking not working properly.

Styled components faces this issue:  https://github.com/styled-components/styled-components/pull/2797#issuecomment-574955289

Does RNW's Babel plugin work on node module imports too? For instance, when we import X from `react-native` in `dripsy`, does it pick that up? I'm not familiar with Babel/webpack etc. 

For now, I'll add `sideEffects: false` to the `package.json` to see if that does anything.

**Comment by cmaycumber** [comment]
That is interesting. I know we are also importing * from @expo/html-elements. Maybe that could be an issue as well especially if the library utilizes more RNW under the hood.

I can also run the bundle analyzer on the gatsby site and normal expo web project I'm working on with dripsy and see if I get the same result.

**Comment by nandorojo** [comment]
> I know we are also importing * from @expo/html-elements.

True, I’ll change this as well.

**Comment by nandorojo** [comment]
Published `1.0.6` that removes the expo * imports.

**Comment by nandorojo** [comment]
I'm still getting all of RNW importing on all of my next js pages. Dripsy takes up only 5kb gzipped, but RNW is 100kb, so not ideal. I'll see if making a page without dripsy has the same effect or not...

**Comment by nandorojo** [comment]
I can't seem to narrow this down to Dripsy, so I'm going to close for now. I do want to figure out what's causing it, though, so I'll be drilling down more shortly.

**Comment by nandorojo** [comment]
Okay, so I finally am looking into this. I'm doing some intensive testing on fresh projects. Here's my first finding:

For a Next.js app, using `<SSRStyleReset />` in `pages/_document.tsx`, as shown in the example, breaks tree shaking and imports all of RNW.

Without using `<SSRStyleReset />`, `_document.js` is like 172kb:

<img width="965" alt="Screen Shot 2021-04-06 at 8 07 52 PM" src="https://user-images.githubusercontent.com/13172299/113792503-15741000-9714-11eb-96f5-c53f0dc9a9ae.png">

With it, this increases to like 600+, and it imports all of RNW:

<img width="1480" alt="Screen Shot 2021-04-06 at 8 08 03 PM" src="https://user-images.githubusercontent.com/13172299/113792535-2c1a6700-9714-11eb-835b-87209f2a8ba9.png">

Clearly having `sideEffects: false` in our `package.json` is insufficient.

**Comment by nandorojo** [comment]
Alright, here is _some_ progres. In Dripsy 1.5.4, I decoupled the fresnel code from React Native.

By changing the import to this:

```js
import { SSRStyleReset } from '@dripsy/core/lib/module/provider/fresnel'
```

My _document.js file no longer imports all of RNW:

<img width="1920" alt="Screen Shot 2021-04-06 at 8 44 48 PM" src="https://user-images.githubusercontent.com/13172299/113794619-f7f57500-9718-11eb-989b-21003740fc50.png">

I'm wondering if changing our build process to [`expo-module-scripts`](https://github.com/expo/expo/tree/master/packages/expo-module-scripts) could fix this. `@expo/html-elements` uses this, for instance. I'm going to see what happens if I import [`@expo/html-elements`](https://github.com/expo/expo/tree/master/packages/html-elements).

**Comment by nandorojo** [comment]
Okay, really getting somewhere:

This **does not** import all of react-native-web:

```js
import { H1 } from '@expo/html-elements' 
```

This **does**:
```js
import { H1 } from 'dripsy' 
```

I wonder if this is due to our packager. I think it could definitely be worth trying `expo-module-scripts` and seeing what that changes.

Another example, this does **not** break tree shaking:

```js
import { Link } from 'expo-next-react-navigation'
```

That's a component from another library of mine, which uses `expo-module-scripts`. The changes would be very minor I believe.

**Comment by nandorojo** [comment]
Okay, definite improvements since switching to `expo-module-scripts`.

I can now import `SSRStyleReset` directly from `dripsy`, and the module size only increases 1kb. Importing React Native components themselves interestingly still increases the bundle size a lot. But my page is now 391.58 KB, compared to 654 KB before. Getting better...

<img width="235" alt="Screen Shot 2021-04-06 at 10 07 24 PM" src="https://user-images.githubusercontent.com/13172299/113800179-802d4780-9724-11eb-8d38-aeb53141bca9.png">

**Comment by cmaycumber** [comment]
> Okay, definite improvements since switching to `expo-module-scripts`.
> 
> I can now import `SSRStyleReset` directly from `dripsy`, and the module size only increases 1kb. Importing React Native components themselves interestingly still increases the bundle size a lot. But my page is now 391.58 KB, compared to 654 KB before. Getting better...
> 
> <img alt="Screen Shot 2021-04-06 at 10 07 24 PM" width="235" src="https://user-images.githubusercontent.com/13172299/113800179-802d4780-9724-11eb-8d38-aeb53141bca9.png">

This is elite.

**Comment by nandorojo** [comment]
It's published on the latest version of Dripsy. 

Unfortunately it looks as though other packages I'm relying on are in fact breaking tree shaking lol. But I'll have to find those one by one and maybe give PRs if they're open to it. Seems like React Native Paper is one, so I might completely remove that since I only use like a button once.

**Comment by nandorojo** [comment]
I'll do some investigations with Moti, I assume the same is happening there. Unfortunately it imports from Reanimated, which I believe _also_ breaks tree shaking...so we'll see about that. Maybe I can fork reanimated and add `expo-module-scripts` here too, but they might have some custom things they use.

**Comment by nandorojo** [comment]
I'll use #84 to track other packages that break tree shaking too. So far:

- react-native-safe-area-context
- @expo/vector-icons (I think) but this might be due to all the fonts being exported no matter what. Not sure.

**Comment by nandorojo** [comment]
Sent a PR to `react-native-safe-area-context`. It reduced my bundle size by 400kb 🤯

https://github.com/th3rdwave/react-native-safe-area-context/pull/189#issuecomment-815274313

**Comment by nandorojo** [comment]
Another instance of this is `@react-navigation/core`.

I use `<NavigationContainer>` in my `pages/_app.tsx` for Next.js.

This is without `NavigationContainer`:

<img width="237" alt="Screen Shot 2021-04-08 at 11 44 43 AM" src="https://user-images.githubusercontent.com/13172299/114057487-993b1300-9860-11eb-9929-5892f669d52c.png">


And this is with `NavigationContainer`:

<img width="215" alt="Screen Shot 2021-04-08 at 11 45 36 AM" src="https://user-images.githubusercontent.com/13172299/114057233-62fd9380-9860-11eb-9e81-3bc4b24e1801.png"> 

I could try forking `@react-navigation/core` to see if using `expo-module prepare` instead solves this.  700kb is a lot.

**Comment by cmaycumber** [comment]
Were you able to solve your bundle size issues? I'm running into something similar trying to get them down a bit.

**Comment by nandorojo** [comment]
Kind of, it’s incredibly shaky. Basically every package I use causes all of RNW. @evanbacon said it’s kind of on the library authors to optimize for tree shaking.

**Comment by cmaycumber** [comment]
> Kind of, it’s incredibly shaky. Basically every package I use causes all of RNW. @EvanBacon said it’s kind of on the library authors to optimize for tree shaking.

Yeah, I kinda expected that. Thanks for letting me know though, hopefully it gets better as RNW gets adopted more and people start paying attention to the bundle sizes.
