### ISSUE TITLE
Combine multiple variants/modifiers

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/dripsy#42]
The option to use multiple variants / modifiers has been discussed at length on `theme-ui`. However, to my understanding, this hasn't been implemented anywhere yet. While I like to stay within the `theme-ui` spec for this library, I'm not sure if it's worth waiting for an implementation on their end.

I think this issue could serve as a way to think through the best way to do multiple `variants` (or `modifiers`) on components. An array syntax is a bit tricky, since it's already used for responsive styles. An alternative could be comma-separated strings, but it's not pretty, and there's no type support there (unless we use some intense TS 4.1 template literals.)

Related discussions from theme UI: https://github.com/system-ui/theme-ui/issues/403

Since we're considering building opinionated UI libraries on top of Dripsy, this seems like essential functionality to avoid tons of boilerplate.

To illustrate the need, consider the difficulty of building all the buttons on this page with multiple modifiers vs. without: https://react.geist-ui.dev/en-us/components/button

**Comment by cmaycumber** [comment]
This is one feature that I've been hoping to see in theme-ui for awhile.

I think that you're right this is a super important problem and really essential when trying to add a wide variety of components that are all themeable from the theme file.

One potential argument for the array syntax is the lack of potential changes to the variants across sizes (For example a button changing from primary to secondary because of screen size are rare in my experience.) and the ability to add responsive styles across different variants.

**Comment by nandorojo** [comment]
> One potential argument for the array syntax is the lack of potential changes to the variants across sizes (For example a button changing from primary to secondary because of screen size are rare in my experience.) and the ability to add responsive styles across different variants.

That’s true. I could see padding or font size changing. But now that I think about it, an array syntax that just merges the variants (where last takes precedent) could work.

**Comment by nandorojo** [comment]
I’ll put together a PR for this to test it out. I think it’s pretty essential for the UI library, and I’d like to try it out with the `geist` example.

**Comment by cmaycumber** [comment]
Another potential solution that I think would be very extensible and keep the array syntax for responsiveness but would stray slightly from the base theme-ui structure would be allowing multiple "variant" keys in the top level theme-key object. 

### For example: 

#### theme.ts:
```js
const theme = {
 buttons: {
  variant: {
    primary: ...,
    secondary: ...,
  },
  size: {
   large: ...,
   base: ...,
   small: ...,
 }
}
```

#### Usage: 
```jsx
...
<Button sx={{
  variant: 'primary',
  size: ['large', 'base', 'small']
}}/>
...
```

**Comment by nandorojo** [comment]
That could definitely work, it just might stray a bit from the actual theme ui spec of simple variants in each key. I started a PR using a simple array syntax. Since they can merge from right-to-left, it seems like a simple mental model, kind of like CSS classes. I've been playing around with it, and so far it feels like a really easy mental model.

For UI elements, I figure it'll end up being something like this:

```tsx
function ThemedCard({ large, outline }) {
  return <Card variants={[large && 'large', outline && 'outline']} />
}
```

**Comment by nandorojo** [comment]
This is published, been working with it so far and I really like it. I don't really use responsive styles in variants to begin with, but even so, the array syntax is pretty easy to understand.

**Comment by cmaycumber** [comment]
Sweet definitely have to try this out when I get the chance.
