### ISSUE TITLE
Investigate changing default flex basis for views

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/dripsy#44]
RNW 0.14 is changing the default flex basis for `View` to match the web spec, since RN is not yet compliant. I wonder if, once expo supports RNW 0.14, the view dripsy exports should change its default. This would ensure cross platform consistency without extra changes.

See: https://github.com/necolas/react-native-web/issues/1640 & https://github.com/necolas/react-native-web/issues/1719

**Comment by cmaycumber** [comment]
Do you think that this would have an impact on how the web container behaves?

**Comment by nandorojo** [comment]
Good question, we’ll definitely have to look into that. In either case, the default behavior for RNW is changing, so we can adjust the web container accordingly if we need. I won’t be upgrading to 0.14 for some time, so I’ll have plenty of time for testing. I am still having some trouble testing this repo’s source code in the Next.js example, but I’ll test this out more with RNW 0.14 once I manage to get a better workflow there.

**Comment by nandorojo** [comment]
I'm using RNW 0.14 and have seen no change in my app at all.
