### ISSUE TITLE
Responsive styles from multiple places don't merge properly

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/dripsy#45]
# What 

Responsive style arrays work totally fine. However, if you use them in `styled`, and then in the `sx` prop too, they don't merge properly. 

```tsx
const Box = styled(View)({
  height: [100]
})

<Box sx={{ height: 150 }} />
```

The example above should end up with a height of 150, but it doesn't. If you do this, however, it does work:

```tsx
<Box sx={{ height: [150] }} />
```

Why? Because `sx` is the dominant style input, but responsive styles take precedent at the moment. So it goes normal styles, merged in order -> any responsive styles, merged in order. The intended behavior is normal styles + responsive styles => merged in order.

# What's happening

It looks like the merging of `responsiveSSRStyles` on web isn't merging the different breakpoints, but rather just using the senior-most set of responsive styles. That is, if you use _any_ responsive styles in `sx`, they will currently override _all_ responsive styles declared in `styled`. This is of course not intended, and should be fixed. Styles should merge in order in general.

# Solution

The problem is that `mapPropsToStyledComponent` simply spreads the objects. Instead, it should explicitly create a `responsiveSSRStyles` array which matches the length of the total number of possible breakpoints. Then, for each index, it should spread the responsive styles from each style input.

This all goes down at https://github.com/nandorojo/dripsy/blob/master/src/css/index.tsx#L546.

**Comment by nandorojo** [comment]
The code has changed, the line is now https://github.com/nandorojo/dripsy/blob/fdc3a9833c0823a8a7ed3b7172ba118ea5e269e4/src/css/index.tsx#L691

**Comment by cmaycumber** [comment]
Do you think that @lodash/merge or the merge function exported from theme-ui could help with this at all?

**Comment by nandorojo** [comment]
Fixed with v2 now that we don't use fresnel.
