### ISSUE TITLE
[question] Since dripsy works with Expo, by extension does it work with React Native?

### ISSUE THREAD

**Issue by 509dave16** [nandorojo/dripsy#47]
Just want to make sure that `dripsy` works with vanilla React Native considering this package is advertised as compatible with Expo & React Native Web. Thanks!

**Comment by nandorojo** [comment]
Yup! I mostly mention Expo since it's where I typically use it. I can update the readme to reflect that. We're working on a separate site for docs too, so I'll mention it there as well.

**Comment by 509dave16** [comment]
@nandorojo Perfect! My employer is working on transitioning away from a hybrid Vue.js app to React Native. And we're hoping to use `dripsy` to facilitate responsive server side rendering for React Native Web. We were looking at [fresnel](https://github.com/artsy/fresnel) by Artsy which unfortunately doesn't work in React Native since it uses CSS media queries and `display: none` . But I notice that for SSR, `dripsy` uses `fresnel`, which is awesome! It's great that `dripsy` acts as an abstraction the web and native platforms.

**Comment by nandorojo** [comment]
Definitely. I've been using Dripsy in production with Next.js for a few months and it's great. I spent a lot of time thinking through how to get SSR and React Native to play nicely together, and Fresnel was a nice abstraction.

To learn more about the usage, I recommend checking out the SSR [release notes](https://github.com/nandorojo/dripsy/issues/34). The discussion on this [PR](https://github.com/nandorojo/dripsy/pull/14#issuecomment-697006135) walked through a lot of the problems we originally faced.

**Comment by 509dave16** [comment]
@nandorojo Appreciate the information on your usage of `dripsy` and more details concerning the motivations. Thanks! I'll go ahead and close the issue to keep your issue count down ;) !!
