### ISSUE TITLE
Are color modes actually supported on native?

### ISSUE THREAD

**Issue by karlsander** [nandorojo/dripsy#49]
The readme mentions that dark mode / color modes are supported, but I can't seem to make it work. Dripsy doesn't export a `useColorMode` hook and `initialColorModeName` and `useColorSchemeMediaQuery` seem to have no effect. Am I doing something wrong?

I think full support should be doable by now, using the Appearance API.

**Comment by nandorojo** [comment]
Hey thanks for the issue. I believe this is supported but not documented well yet. Could you try this?

```js
import { useDripsyTheme } from 'dripsy'

const { setColorMode, colorMode } = useDripsyTheme()
```

**Comment by alz10** [comment]
@nandorojo Hi, how do you implement that in a class component?

**Comment by nandorojo** [comment]
I would wrap it with a function component, put the hook in the function component, and pass the color mode functions down as props.

You can find an example [here](https://reactnavigation.org/docs/use-theme/#using-with-class-component).

**Comment by alz10** [comment]
@nandorojo can you check? I'm getting undefined, sorry I'm new to hooks  https://snack.expo.io/@coffeeprince/dripsy-dark-mode

**Comment by nandorojo** [comment]
The hook has to be nested within the provider. Here you put the hook outside of it.

**Comment by alz10** [comment]
@nandorojo it's undefined even inside the functional component, check the console log https://snack.expo.io/@coffeeprince/dripsy-dark-mode

**Comment by nandorojo** [comment]
The hook can only be called in a component that is the child of `DripsyProvider`. Here, you're putting the hook in the same component as the provider.

**Comment by dackom** [comment]
Hello, I have same/similar issue:
`<DripsyProvider theme={theme}>
 <App />
</DripsyProvider>
`

Inside the app component I have:
`const { setColorMode, colorMode, theme } = useDripsyTheme();`
`console.log(setColorMode, colorMode, theme);`

That console log outputs: undefined, undefined, {...mythemeobject...}

In this case app is direct child for dripsyprovider component, I get same thing when it's not direct child.

**Comment by nandorojo** [comment]
Does your theme have multiple color modes

**Comment by dackom** [comment]
Does it need to have?

export const theme = {
  colors: {
    text: '#0F0',
    background: '#fff',
    modes: {
      dark: {
        text: '#FFF'
      }
    }
  },
  text: {
    a: { color: '#00F', fontSize: 16, margin: 10 },
    link: { color: '#F00', fontSize: 16, margin: 10 }
  }
};

**Comment by nandorojo** [comment]
@cmaycumber have you used color modes in your app? I haven't actually. Maybe there's a localstorage flag to disable or something?

**Comment by dackom** [comment]
Hm... I see in dripsy code:
`export { useThemeUI as useDripsyTheme } from 'theme-ui'`
But here: https://theme-ui.com/color-modes, they are saying:
`const [colorMode, setColorMode] = useColorMode()` 

Dripsy doesn't have `useColorMode` in its code?

**Comment by nandorojo** [comment]
You can try importing that from theme ui directly and see if it works.

**Comment by dackom** [comment]
`Error: [useColorMode] requires the ColorModeProvider component`
