### ISSUE TITLE
Is the SSRStyleReset export deprecated? Cannot find in source code of dripsy node_module

### ISSUE THREAD

**Issue by 509dave16** [nandorojo/dripsy#50]
Hey, @nandorojo ! Where does the `SSRStyleReset` named export get exported from in the codebase? Is it coming from another package?? I can't seem to find seem to find it in `dripsy` codebase.

**Comment by nandorojo** [comment]
Make sure you get the casing correct if you're trying to import it. Make sure you're also on the newest version.

It's in the /provider.

**Comment by 509dave16** [comment]
@nandorojo Found it. Thanks!
