### ISSUE TITLE
<P> is not exported

### ISSUE THREAD

**Issue by JackCA** [nandorojo/dripsy#52]
The docs r[eference being able to use `<P>`](https://github.com/nandorojo/dripsy/commit/14bf9c2a9cd6e42dafe53e0ca31851dee73c1182) html-elements but it looks like it's not exported from [components](https://github.com/nandorojo/dripsy/commit/14bf9c2a9cd6e42dafe53e0ca31851dee73c1182)

**Comment by nandorojo** [comment]
Good catch, I'll update.

**Comment by nandorojo** [comment]
Added in `1.4.4`

**Comment by JackCA** [comment]
incredible 120 second fix!
