### ISSUE TITLE
Consider Size component

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/dripsy#56]
I'm wondering if there should be a `Size` component, whose explicit role is to let us size items consistently without using `webContainerSx`. I made something like it in my app, and I'm wondering if it should be included in Dripsy directly.

## Examples

For flex columns:

```tsx
import { Size } from 'dripsy'

<Row>
  <Size flex={[null, 1]}>
    <Column />
  </Size>
  <Size flex={[null, 1]}>
    <Column />
  </Size>
</Row>
```

For widths:

```tsx
<Size width={['50%', '33%']} />
```

## Why

At the moment, the same thing is achieved by passing a `webContainerSx` prop. It's a bit cumersome and repetitive. I think it's a nice escape hatch prop to have, but for sizing, it makes more sense to have a specific solution.

Since the entire `sx` prop would not be supported, style props would be inlined on the `Size` component.

## Code

On native, it would export a `View` from dripsy, like normal (with added props.) Nothing special happening on native.

**size.tsx**
```tsx
import View from './view'

type SizeProps = Pick<SxStyleProp, 'flex' | 'width' | ...etc>

const Size = (props: SizeProps) => {
  return <View sx={props} />
}
```

On web, however, we can render a native `div`, and use `sx` with the JSX pragma from `theme-ui`.

**size.web.tsx**
```tsx
/** @jsx jsx */
import { jsx } from 'theme-ui'

const RNWStyleReset = {...}

const Size = (props: SizeProps) => {
  return <div sx={{ ...RNWStyleReset, ...props }} />
}
```

**Comment by cmaycumber** [comment]
This seems pretty useful. I know I would personally use it, I think it cleans up the code quite a bit compared to the webContainerSx prop.

> At the moment, the same thing is achieved by passing a webContainerSx prop. It's a bit cumersome and repetitive. I think it's a nice escape hatch prop to have, but for sizing, it makes more sense to have a specific solution.

I agree with this. It's not always intuitive right off the bat.

**Comment by nandorojo** [comment]
While I'm using this my app, I'm still not sure if I'm convinced by it. I think getting rid of SSR (and thus fresnel) would be a better idea than entirely circumventing RNW altogether :/

**Comment by cmaycumber** [comment]
> While I'm using this app, I'm still not sure if I'm convinced by it. I think getting rid of SSR (and thus fresnel) would be a better idea than entirely circumventing RNW altogether :/

I would have to agree. Leaving out SSR would be a bummer but this would make the API a bit more intuitive.

**Comment by nandorojo** [comment]
Yeah. And like I mentioned earlier, my app doesn't even have SSR. One of my providers delayed rendering until after mounting, so BeatGig has never even had SSR 😂 

I spent all this time making Dripsy support SSR, only to find that I didn't even need it, because my site is fast enough without it. Also, it hasn't harmed us with Google at all.

I still use SSR for SEO meta tags, but I put these at the root before rendering any providers anyway, thanks to `pages/_app.js` from next.js.

**Comment by cmaycumber** [comment]
> Yeah. And like I mentioned earlier, my app doesn't even have SSR. One of my providers delayed rendering until after mounting, so BeatGig has never even had SSR 😂
> 
> I spent all this time making Dripsy support SSR, only to find that I didn't even need it because my site is fast enough without it. Also, it hasn't harmed us with Google at all.
> 
> I still use SSR for SEO meta tags, but I put these at the root before rendering any providers anyway, thanks to `pages/_app.js` from next.js.

That's good to know. This makes me feel a little bit more comfortable building with Dripsy w/o the serverside features, plus most of the content would probably still render server-side (if it's the same on mobile/desktop), just wouldn't be styled correctly.

**Comment by nandorojo** [comment]
Yeah, that's true. Although I would recommend returning null and then rendering the app after it's mounted if you ever plan on using responsive styles. I'll probably do this with an `ssr` prop on the provider.

Ultimately, we're dealing with constraints of RNW.
