### ISSUE TITLE
Add Pressable Component

### ISSUE THREAD

**Issue by martinjuhasz** [nandorojo/dripsy#57]
Would be nice if dripsy could export the `Pressable` component from `react-native`.

Sometimes the `A` component is not sufficient and one would like to use the `Pressable`.
If i get it right, its basically a `View` component.

```
import { Pressable as RNPressable } from 'react-native'
import { createThemedComponent } from 'dripsy'

export const Pressable = createThemedComponent(RNPressable)
```

works fine for me.

**Comment by cmaycumber** [comment]
I think this would be an easy fix! It's definitely something useful. I currently do the same thing more my apps.

I'm sure @nandorojo would have no problem approving a PR for this.

**Comment by nandorojo** [comment]
Yeah, I agree. I was waiting for people to catch up on upgrading to RNW 0.14 before adding it in.

This is the code I'm using in my app now. Happy to add it to Dripsy along with #48 

```tsx
import React, { ReactNode, ComponentProps } from 'react'
import { styled } from 'dripsy'
import {
  Pressable as NativePressable,
  PressableStateCallbackType,
  ViewStyle,
} from 'react-native'

type CallbackWithHovered = PressableStateCallbackType & { hovered?: boolean }
const StyledPressable = styled(NativePressable)({})

type Props = {
  style?: ((prop: CallbackWithHovered) => ViewStyle) | ViewStyle
  children?: ReactNode | ((prop: CallbackWithHovered) => ReactNode)
} & Omit<ComponentProps<typeof StyledPressable>, 'children' | 'style'>

export default React.forwardRef(function Pressable(
  { sx = {}, ...props }: Props,
  ref: ComponentProps<typeof StyledPressable>['ref']
) {
  return (
    <StyledPressable
      {...props}
      ref={ref}
      sx={{
        cursor:
          props.onPress || props.accessibilityRole === 'link'
            ? 'pointer'
            : 'default',
        ...sx,
      }}
    />
  )
})
```

**Comment by martinjuhasz** [comment]
It really depends on how you want to alter the default behaviour of both, the react-native component and theme-ui's `sx` property.

```
<Pressable sx={({ hovered, pressable }) => ({ bg: hovered ? 'primary' : 'text' })}>
  This isn't supported yet.
</Pressable>

```
I guess this is not possible in theme-ui, right? If so, i would leave it to the developer to implement the switching of style props. But this is my personal opinion to keep this library as close as possible to theme-ui's syntax.



Other question regarding your code:
```
<Pressable>
  {({ hovered, pressable }) => ...}
</Pressable>
```
This is also not possible using the default react-native `Pressable` component right? Looking at your implemention, i'm wondering where you call the functionChild and supply those properties? Esp `hovered` ?

**Comment by nandorojo** [comment]
React Native Web 0.14 extends `Pressable` to include `hovered`

**Comment by nandorojo** [comment]
See https://github.com/necolas/react-native-web/issues/1719

**Comment by nandorojo** [comment]
Thanks @cmaycumber for this!

**Comment by nandorojo** [comment]
Here's an example using the `style` prop as a function too (this only works in Dripsy v2!)

```js
import { useSx } from 'dripsy'
import { Pressable } from 'react-native' // or dripsy!
```

```jsx
const sx = useSx()

return (
  <Pressable 
   style={({ hovered }) => sx({ color: hovered ? 'primary' : 'secondary', px: [2, 3] }))} 
  />
)
```
