### ISSUE TITLE
theme.customFonts doesn't seem to work

### ISSUE THREAD

**Issue by zilahir** [nandorojo/dripsy#63]
First of all, I am in love with this project! :) 

I am trying to use custom fonts, and it seems, by defining font in the `theme.customFonts`, and then referencing it in the `fonts` doesn't seem to do its job. 

So let's consider the following: 

```js
customFonts: {
    inter: {
      bold: "Inter-Bold",
      default: "Inter-Regular",
      normal: "Inter-Regaulr",
      "400": "Inter-Regular",
      "300": "Inter-Thin",
      "500": "Inter-Medium",
      "600": "Inter-Medium",
      "700": "Inter-SemiBold",
    },
  },
  fonts: {
    root: "inter",
  },
``` 

Of course, the assets are loaded, using the `Font.loadAsync(fonts)` in a custom provider.

This throws the following error: 

>fontFamily "inter" is not a system font and has not been loaded through Font.loadAsync.
If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

The weird thing, if i change it like this: 

```
fonts: {
    root: "Inter-Bold",
  },
```

The font changes to bold. This works though both ob the device and in the browser, so that's good. 

Any idea how to get around on this? 

Thank you in advance!

**Comment by nandorojo** [comment]
Can you show your expo font loader code?

**Comment by nandorojo** [comment]
I'm currently snowboarding so I'm going to send a screenshot lol.

Did you see this in the docs?

![image](https://user-images.githubusercontent.com/13172299/103142749-ed1d5400-46d6-11eb-8961-31e1d6c3e773.png)

**Comment by zilahir** [comment]
Hey! Thanks for replying :) Marry Christmas! 

Yes, I've seen that in the docs, and the reason I haven't shared the font loading method, because I could verify the fonts being loaded correctly: 

```
fonts: {
    root: "Inter-Bold",
  },
```

So this, indicates that the `Inter-Bold` font loaded correctly, and the error message is gone. 

I have a custo wrapper to load async, you  can check it [here](https://gist.github.com/zilahir/5f83277f706e6c77636db7dc4869d380)

**Comment by nandorojo** [comment]
It's hard for me to help without seeing a simple reproduction of the docs not working. Could you see if loading it in the way the docs say with expo font works?

One thing to keep in mind: when you load in the font with expo fonts, the name of the normal weight font should be `inter`. The name of the imported font is important.

**Comment by zilahir** [comment]
@nandorojo sorry for the late answer. I am loading the fonts as its described in the expo dosc, using `Fonts.loadAsync`. 

This is the Object, that stores the fonts, and being passed to the `loadAsync` promise: 

```
const fonts = {
  "Inter-Black": require("./assets/fonts/Inter/Inter-Black.ttf"),
  "Inter-Bold": require("./assets/fonts/Inter/Inter-Bold.ttf"),
  "Inter-ExtraBold": require("./assets/fonts/Inter/Inter-ExtraBold.ttf"),
  "Inter-ExtraLight": require("./assets/fonts/Inter/Inter-ExtraLight.ttf"),
  "Inter-Light": require("./assets/fonts/Inter/Inter-Light.ttf"),
  "Inter-Medium": require("./assets/fonts/Inter/Inter-Medium.ttf"),
  "Inter-Regaular": require("./assets/fonts/Inter/Inter-Regular.ttf"),
  "Inter-SemiBold": require("./assets/fonts/Inter/Inter-SemiBold.ttf"),
  "Inter-Thin": require("./assets/fonts/Inter/Inter-Thin.ttf"),
};
```

And then: 

```
const useLoadAssets = (assets: number[], fonts: FontSouce): boolean => {
  const [ready, setReady] = useState(false);
  usePromiseAll(
    [Font.loadAsync(fonts), ...assets.map((asset) => Asset.loadAsync(asset))],
    () => setReady(true)
  );
  return ready;
};
```

So you say: 

> One thing to keep in mind: when you load in the font with expo fonts, the name of the normal weight font should be inter. The name of the imported font is important.

If i understand this correctly, the `Inter-Regular` in this object should be `Inter` as that will be the _default_ font. 

```
const fonts = {
  "Inter-Black": require("./assets/fonts/Inter/Inter-Black.ttf"),
  "Inter-Bold": require("./assets/fonts/Inter/Inter-Bold.ttf"),
  "Inter-ExtraBold": require("./assets/fonts/Inter/Inter-ExtraBold.ttf"),
  "Inter-ExtraLight": require("./assets/fonts/Inter/Inter-ExtraLight.ttf"),
  "Inter-Light": require("./assets/fonts/Inter/Inter-Light.ttf"),
  "Inter-Medium": require("./assets/fonts/Inter/Inter-Medium.ttf"),
  Inter: require("./assets/fonts/Inter/Inter-Regular.ttf"), // HERE
  "Inter-SemiBold": require("./assets/fonts/Inter/Inter-SemiBold.ttf"),
  "Inter-Thin": require("./assets/fonts/Inter/Inter-Thin.ttf"),
};
```

And then, in the `theme`: 

```customFonts: {
    Inter: {
      bold: "Inter-Bold",
      default: "Inter-Regular",
      normal: "Inter",
      "400": "Inter-Regular",
      "300": "Inter-Thin",
      "500": "Inter-Medium",
      "600": "Inter-Medium",
      "700": "Inter-SemiBold",
    },
  },
  fonts: {
    root: "Inter",
  },
```

**Comment by zilahir** [comment]
*UPDATE*: 

Hah! It seems like it's working this way! :)

**Comment by nandorojo** [comment]
Looks like it was because it wasn't capitalized in the theme before. Glad it's working.
