### ISSUE TITLE
Unable to use dripsy with reanimated2

### ISSUE THREAD

**Issue by durgaprasadksv** [nandorojo/dripsy#66]
Thank you for the wonderful library. Its saving us a lot of development time to develop responsive interfaces. However, it is not clear how we can use this library with reanimated. <Dripsy.View as?= /> doesn't seem to work when we pass ```as?={Animated.View}``` 

Can you please suggest how to convert the following animated component to use dripsy. 

```
const Dot = ({ index, currentIndex }: DotProps) => {
  const style = useAnimatedStyle(() => {
    const opacity = interpolate(
      currentIndex.value,
      [index - 1, index, index + 1],
      [0.5, 1, 0.5],
      Extrapolate.CLAMP
    );
    const scale = interpolate(
      currentIndex.value,
      [index - 1, index, index + 1],
      [1, 1.25, 1],
      Extrapolate.CLAMP
    );
    
    return {
      opacity,
      backgroundColor: "#000",
      width: 8,
      height: 8,
      borderRadius: 4,
      margin: 4,
      transform: [{ scale }],
    };
  });

  return <Animated.View style={style} />;
};
```

**Comment by cmaycumber** [comment]
@durgaprasadksv I usually wrap the dripsy view inside the createAnimatedComponent method like so:

```js
Animated.createAnimatedComponent(View)
```

**Comment by nandorojo** [comment]
Yeah, I think that's the move. We should probably edit the readme for this.
