### ISSUE TITLE
Upgrade theme-ui

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/dripsy#68]
Let's upgrade theme-ui to the latest. There are a few breaking changes to keep in mind.

https://github.com/system-ui/theme-ui/blob/develop/CHANGELOG.md

**Comment by cmaycumber** [comment]
Do you think that we should upgrade to the latest alpha version: `v0.6.0-alpha.6`?

**Comment by nandorojo** [comment]
Yeah, I think so. 

I'd also love to support the new `__default` flag in our `css` file: https://github.com/system-ui/theme-ui/blob/develop/CHANGELOG.md#v060-alpha5-2021-01-22

It seems like we'd need to see how they did this and just copy it, since we're using our own `css` function at this point. I doubt it would be that tough, just need to check if `typeof value === 'object && '__default' in value`, I'm guessing.

**Comment by cmaycumber** [comment]
I can try to tackle the upgrade part of this right now and take a look to scope out implementing the `_default` flag.

**Comment by nandorojo** [comment]
Sweet sounds good.
