### ISSUE TITLE
CI/CD Support

### ISSUE THREAD

**Issue by cmaycumber** [nandorojo/dripsy#71]
Adding in some sort of CI/CD might help speed up some of the publishing and development processes.

There was some previous talk about this in #48. I just wanted to open the issue so we can track it.

**Comment by nandorojo** [comment]
Yeah, I think getting `auto` setup could really help speed this up.

**Comment by cmaycumber** [comment]
Mind if I give this a shot mimicking the setup for moti?

**Comment by nandorojo** [comment]
Go for it! I never got `auto` to work there, so I've just been using `lerna`. I've liked it so far; the one thing missing is being able to release from PRs/git pushes. It seems like auto is much more suited for this task (and is now used by theme-ui in 0.6+ I believe). If you could get auto working it would be a homerun.
