### ISSUE TITLE
Add stricter type support

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/dripsy#72]
I'm still waiting on https://github.com/system-ui/theme-ui/pull/1090 to merge, and it seems to be getting hung up.

I think it might be time to upstream theme-ui on types for certain things.

I have 2 goals:

- Provide stricter types that match Dripsy, such as `Theme['customFonts']`
- Let users use declaration merging to type `useDripsyTheme`.
  - I'd like to achieve the same with the `sx` prop, but it's too complicated so I'll wait for the PR above.

# 1) Edit the default `Theme` type, name it `DripsyTheme`

For starters, I'd like to override the default `Theme` type exported from `theme-ui`, which does not include `dripsy`'s `customFonts` key in the theme.

As we can see [here](https://github.com/byCedric/office-marathon/blob/148458d87f74cb4ef340f136ab36ec4f523b1968/src/providers/theme.tsx#L19) in this app by @byCedric, `customFonts` isn't included in the type, so you need to either ignore `Theme`, or make it a separate type. This doesn't seem ideal.

```ts
// types.ts
import type { Theme } from 'theme-ui'

export interface BaseDripsyTheme extends Theme { customFonts: { ... } }
```

## Custom Font type implementation

Since Dripsy has strict requirements for custom fonts, it would be nice to enforce them with types too:

```ts
export interface BaseDripsyTheme<FontFamilyKeys extends string> extends Theme {
  customFonts?: { [key in FontFamilyKeys]?: Record<string, string> }
  fonts?: {
    [key: string]: FontFamilyKeys | undefined
    ['root']?: FontFamilyKeys
  }
}
```

Unfortunately, it seems like this code sample [doesn't actually work](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=36&pc=2#code/JYOwLgpgTgZghgYwgAgCoAsIFsUG8C+AUIaJLIigEJwDOEAIlMAA40CeG2EnOAPAGIB7cPzhZgAGzYBpCGxrIIAD0ggAJgppgmIAOYA+RSojqFPPIWRXkCAK5bBWIeBoB+AFzJcl674DaANZyyKDIzmCi4lKy8gC6HsgAShAIglBqvFo6ugA0yFmgBj5WRL4wwmBunt6+-kFsngV6sZ7hkZIycgoAPsi26hAwoBBqxbVQgoJgCW1iHTE0Y0RExISpIFrIYJg4ntR0jCzs5ua8AOQIwFB2EnBQZ4YAvF5jdg5OFTTVY76X17a3KDfWog5BnEBpLBwCRnTwXK43O4AWi0aiRACNJgEzj9rKU8TkxuUXMDQRMpnC-oj7ktCCsAPT0kIwZAAdxQamEZzAyDgajUyAARFSAXdBUZmBJgJcwFI8sAeayuYq0gE1sJNnBbGBBOY9rQGExWBwdtxTchnjVrG8dR8SS9QTYEaKgQ7HdZwZDobCwSLASiwGjMYJsbiSktCWVPqSQeSwJTnYCcb5lkA) as intended, so I'd love suggestions on that.

# 2) Provide strict types for `useDripsyTheme`

As it stands, `useDripsyTheme` has relatively weak typings. At the very least, I'd like it to piggy back off of 1) above, like so:

```ts
// use-dripsy-theme
import { BaseDripsyTheme } from './types.ts'

export default function useDripsyTheme() {
  return (useThemeUI() as any) as Omit<ReturnType<typeof useThemeUi>, 'theme'> & { theme: BaseDripsyTheme }
}
```

Here, we at least get the `customFonts` field with `useDripsyTheme`.

**However**, I think we could take it a step further with declaration merging. This is what https://github.com/system-ui/theme-ui/pull/1090 intends to achieve for the `sx` prop. In the meantime, I think we can hack our way around it for `useDripsyTheme`.

# Strict types implementation

Imagine we have this theme:

```ts
const theme = {
  colors: {
    primary: 'red',
    'primary-dark': 'darkred'
  }
}
```

A fair expectation from the user should be this:

```ts
const { colors } = useDripsyTheme().theme

const textColor = colors.primary // red
```

I think it could be achieved with this kind of solution:

## Step 1: Dripsy creates a `makeTheme` function:

An example looks like [this](https://github.com/system-ui/theme-ui/pull/1090/files#diff-760c5b9e7cb02deed65c4ed00d1a9afde0da1cb9c1d55c632a8c96f327c9f327) from theme-ui's upcoming PR.

```ts
// this is from #1 up above
import { DripsyTheme } from './types'

export const makeTheme = <T extends DripsyTheme>(t: T) => t
```

## **Step 2:** Dripsy exports `CustomDripsyTheme`

Theme-ui plans to call this [`UserTheme`](https://github.com/system-ui/theme-ui/blob/6f947306e168795e14978776948a9d9c5c1469e5/packages/css/src/types.ts#L39), so once they do, we can merge them somehow, but this way we don't collide.

```ts
/**
 * Can be augmented by users to inject their exact theme into Dripsy types.
 */
export interface CustomDripsyTheme {}
```

## **Step 3:** Users create their theme with `makeTheme`:

```ts
const myTheme = makeTheme({
  colors: {
    primary: 'red',
    'primary-dark': 'darkred'
  }
})

type MyTheme = typeof myTheme
declare module 'dripsy' {
  // this overrides the empty CustomDripsyTheme that Dripsy exports
  export interface CustomDripsyTheme extends MyTheme {}
}
```

## Step 4. Make `FinalDripsyTheme`

We can combine the original `BaseDripsyTheme` with `CustomDripsyTheme`:

```ts
import type { Theme } from 'theme-ui'

export interface BaseDripsyTheme extends Theme { customFonts: { ... } }

export type Assign<T, U> = {
  [P in keyof (T & U)]: P extends keyof U
    ? U[P]
    : P extends keyof T
    ? T[P]
    : never
}

export interface DripsyTheme extends Assign<BaseDripsyTheme, CustomDripsyTheme> {}

// For backwards-compatibility, name Theme too
export type Theme = DripsyTheme
```

_The code above is taken from theme-ui [here](https://github.com/system-ui/theme-ui/blob/6f947306e168795e14978776948a9d9c5c1469e5/packages/css/src/types.ts#L41)._

Now that we have this `DripsyTheme` created, we can use that in `useDripsyTheme`:

```diff
// use-dripsy-theme
- import { BaseDripsyTheme } from './types.ts'
+import { DripsyTheme } from './types.ts'
```

```ts
// use-dripsy-theme

export default function useDripsyTheme() {
  return (useThemeUI() as any) as Omit<ReturnType<typeof useThemeUi>, 'theme'> & { theme: DripsyTheme }
}
```

**Comment by nandorojo** [comment]
This should work in a `@dripsy/theme` package one @cmaycumber's #74 gets merged, will try to get to merging that when I can.

**Comment by JackCA** [comment]
@nandorojo it looks like #74, does that help push this along at all?

PS: You've been doing really great work on the recent releases!

**Comment by nandorojo** [comment]
Yeah, I haven't really had time to work on this. At the moment, I'm just using this in my app:

```js

import { useDripsyTheme } from 'dripsy'
import type { DripsyTheme } from './index'

export default function useTheme() {
  return (useDripsyTheme().theme as any) as DripsyTheme
}
```

**Comment by nandorojo** [comment]
This will be added in v3. See #124 🥳
