### ISSUE TITLE
LinearGradient component

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/dripsy#73]
I recently came across this beautiful landing page from auth0: https://auth0.design/

It included these cool gradients:

<img width="1841" alt="Screen Shot 2021-02-11 at 11 06 28 AM" src="https://user-images.githubusercontent.com/13172299/107663528-77a31e00-6c59-11eb-9217-7200db1eab0b.png">

Which reminded me of this [webflow theme](https://panels-template.webflow.io/template/style-guide) I used for the [doorman.cool](https://doorman.cool) website: 

<img width="1439" alt="Screen Shot 2021-02-11 at 11 09 04 AM" src="https://user-images.githubusercontent.com/13172299/107663634-96a1b000-6c59-11eb-8b45-106f93623939.png">

It would be cool to have a `LinearGradient` component in Dripsy, which re-exports Expo's.

```tsx
import { LinearGradient } from '@dripsy/gradient'

// theme colors
<LinearGradient colors={['primary', 'accent']} />
```

Maybe you could even have gradients in your theme.

```tsx
const theme = {
  linearGradients: {
    strong: ['primary', 'secondary']
  }
}

<LinearGradient variant="strong" />
```

The `variant` prop might not be the right one to use here, since we're technically not applying a set of styles, but rather we're using an opinionated mapping of colors -> props.

This might be more appropriate:

```tsx
const theme = {
  linearGradients: {
    strong: ['primary', 'secondary']
  }
}

<LinearGradient gradient="strong" />
```

**Comment by cmaycumber** [comment]
This is super cool. It'd be instantly useful for me, I'm currently using a dripsy + expo-linear-gradient combo myself. 

Mind if I take a crack at this? I can also add in a re-exported Pressable component while I'm at it.

**Comment by nandorojo** [comment]
Definitely, go for it.

This is what I'm using in my app now:

```tsx
import React from 'react'
import { LinearGradient } from 'expo-linear-gradient'
import { styled, useDripsyTheme } from 'dripsy'
type Props = React.ComponentProps<typeof LinearGradient>

const Grad = styled(
  React.memo(
    function Gradient(props: Props) {
      const { colors } = useDripsyTheme().theme
      return (
        <LinearGradient
          {...props}
          colors={props.colors?.map(
            (color) => (colors?.[color] as string) ?? color
          )}
        />
      )
    },
    (prev, next) => JSON.stringify(prev) === JSON.stringify(next)
  )
)({})

export default function Gradient(props: React.ComponentProps<typeof Grad>) {
  return <Grad {...props} />
}
```

The memoizing might not be necessary, but I noticed flickers on web when I didn't do it. Might be better for people to do that in their own apps if they want it and to document it.

Since we're adding a dependency, I think it would be good to make this a `@dripsy/gradient` package. It might also mean we should move `styled` etc to a `@drispy/core` package, the way I did for `moti`.

**Comment by nandorojo** [comment]
I've had issues with wrapping `Pressable`. Its TS types don't lend themselves well to HOCs, so I think we're best off making our own component for it. I think I linked to mine in another issue, but this is it for context:

```tsx
import React, { ReactNode, ComponentProps } from 'react'
import { styled } from 'dripsy'
import {
  Pressable as NativePressable,
  PressableStateCallbackType,
  ViewStyle,
} from 'react-native'

// react-native-web/overrides.ts
declare module 'react-native' {
  interface PressableStateCallbackType {
    hovered?: boolean
    focused?: boolean
  }
  interface ViewStyle {
    transitionProperty?: string
    transitionDuration?: string
  }
  interface TextProps {
    accessibilityComponentType?: never
    accessibilityTraits?: never
  }
}

type CallbackWithHovered = PressableStateCallbackType
const StyledPressable = styled(NativePressable)({})

type Props = {
  style?: ((prop: CallbackWithHovered) => ViewStyle) | ViewStyle
  children?: ReactNode | ((prop: CallbackWithHovered) => ReactNode)
} & Omit<ComponentProps<typeof StyledPressable>, 'children' | 'style'>

const Press = React.forwardRef(function Pressable(
  { sx = {}, disabled, ...props }: Props,
  ref: ComponentProps<typeof NativePressable>['ref']
) {
  return (
    <StyledPressable
      {...props}
      ref={ref as any}
      disabled={disabled}
      sx={{
        cursor:
          props.onPress || props.accessibilityRole === 'link' || !disabled
            ? 'pointer'
            : 'default',
        ...sx,
      }}
    />
  )
})

export default Press
```

Should probably add a `Platform.select` for the cursor style, such that we only show it on web.

**Comment by cmaycumber** [comment]
> Since we're adding a dependency, I think it would be good to make this a @dripsy/gradient package. It might also mean we should move styled etc to a @drispy/core package, the way I did for moti.

Got it.

**Comment by cmaycumber** [comment]
Alright, I'll try to make your code the basis for the pressable component and check out that other issue. We can always tweak as we go.

**Comment by nandorojo** [comment]
One last thing, which is unrelated but I'm seeing on the Pressable code. Our current types for the `ref` prop in `createThemedComponent` are wrong. I'm forced to pass `as any` whenever I pass a `ref` down.

**Comment by cmaycumber** [comment]
How do you think we should start breaking up the main `dripsy` package into smaller packages? I think that's the first PR I'm going to handle so that it's a little more flexible. 

Do you think we should take the current dripsy package and move all of that into `@dripsy/core` or break that out further? Into something like `@dripsy/css`, `@dripsy/utils`, etc.

**Comment by cmaycumber** [comment]
Do you think the gradient prop should replace the color prop entirely? I don't know what the best move would be here is, Otherwise, either the gradient or the colors object needs to take precedence, if we choose this way I think the colors prop should probably take precedence. 

So it could be used like: 

```jsx
const theme = {
  linearGradients: {
    strong: ['primary', 'secondary']
  }
}

<LinearGradient gradient="strong" />
// or
<LinearGradient gradient={['primary', 'secondary']} />
```

Let me know what you think.

**Comment by nandorojo** [comment]
Similar to what you said, here's what I think makes sense:

```jsx
const theme = {
  linearGradients: {
    strong: ['primary', 'secondary']
  }
}

// these are equivalent
<LinearGradient gradient="strong" />
<LinearGradient colors={['primary', 'secondary']} />

// colors prop takes precedence
<LinearGradient gradient="strong"  colors={['accent', 'highlight']}  />
```

**Comment by cmaycumber** [comment]
Got it. That's how I'm currently handling it.

I have this just about done along with another branch for the pressable component if we can get #74 merged in.
