### ISSUE TITLE
Grid component

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/dripsy#75]
I made a responsive grid, and will be integrating it soon when I have time. Here's a preview: https://twitter.com/fernandotherojo/status/1362143823288270848?s=21

**Comment by nandorojo** [comment]
I'll push this once #74 is merged

**Comment by nandorojo** [comment]
I have this made now. However, I'm wondering if this might be better: https://github.com/mobily/stacks

The downside of Stacks is no SSR support. So maybe I'll push this anyway. But Stacks looks much more feature rich.

**Comment by nandorojo** [comment]
Maybe the move is to create a `dripsy/stacks` package that wraps stacks and uses theme values for padding, etc.

**Comment by nguyenkhooi** [comment]
Hey @nandorojo, any update on this issue? Gotta implement this into our dripsy setup as soon as it becomes official. Right now we're settling down with `react-native-super-grid`, but it's  to try your option and compare the performance!

**Comment by nandorojo** [comment]
Have you tried the stacks I linked to? It's much more feature-rich than what I made.
