### ISSUE TITLE
Dripsy View disappears when snapping window to the side on Windows (Win + left/right arrow)

### ISSUE THREAD

**Issue by nguyenkhooi** [nandorojo/dripsy#79]
Playing with dripsy snack, specifically changing cyan View component's height based on breakpoints. One issue, when I snap my window to either side of the screen (Win + left/right arrow), the View disappears! Need to resize the window a little bit to show the View again.

https://snack.expo.io/@nguyenkhooi/dripsy-browser-mockup 

![dripsy snap issue](https://user-images.githubusercontent.com/14075977/111563398-79b54b00-87ca-11eb-825f-1d7f140ebade.gif)

@nandorojo any thoughts on this?

**Comment by nandorojo** [comment]
Well that's certainly interesting. My best guess is that, we're using a `>` condition for the breakpoints, and that it's not including one of them or something, so it skips a pixel. Good find, I'll see if I can reproduce it elsewhere. I have a whole app built and haven't actually seen it show up once oddly.
