### ISSUE TITLE
For "styled", is there a way to use props? 

### ISSUE THREAD

**Issue by jenniferpham** [nandorojo/dripsy#85]
I was hoping to use props inside of `styled`, and I realized I may have been using it wrong.  I assumed it was similar to `styled-components` where one of the arguments was props, but after more reading on your docs, it seems like it's a rewrite of `createThemedComponent`, with the 2 arguments only being `themeKey` and `defaultVariant`.  

Is there a way or workaround to write something like this so I can use props to dynamically change styles? 

```
import React from "react"
import { Text } from "react-native"
import { styled } from "Dripsy"

const Headline = styled(Text, ({ isEnabled, theme }) => ({
  color: isEnabled ? "primary" : "secondary",
  fontSize:  theme.fontSizes[3] // or simply 3 would work too
}))

export default () => <Headline isEnabled={true}>Hello</Headline>
```

**Comment by nandorojo** [comment]
Hi @jenniferpham, looking back into the code, it looks like this already implemented. I think there might be TS issues with it, but it should work. I'm going to close this for now, but feel free to let me know if that works for you or not.

**Comment by nandorojo** [comment]
I've figured out a way to make this work with v2. Will push in the next update.

**Comment by nandorojo** [comment]
Added in `v2.1.0`.
