### ISSUE TITLE
[Question] How to style "non style props" using dripsy ?

### ISSUE THREAD

**Issue by fortezhuo** [nandorojo/dripsy#89]
How to style non style props using dripsy like containerStyle, contentContainerStyle, contentInset, etc ?

```
<ScrollView containerStyle={???} contentContainerStyle={???} />

```

And also how to get theme color from dripsy, and use that color to component  ?

```
<TextInput placeholderTextColor={???} />
```
any hooks / function that can be used ?

**Comment by nandorojo** [comment]
`useDripsyTheme().theme`

**Comment by fortezhuo** [comment]
```useDripsyTheme().theme``` can solve placeholderTextColor.. but I still be confused how inject containerStyle with sx or something similar ?

```
<ScrollView containerStyle={???} contentContainerStyle={???} />
```

**Comment by nandorojo** [comment]
It's not possible for responsive styles without wrapping the components. However, you can use the theme values for color, space, etc and pass them directly to the props.

There was discussion for supporting this here: https://github.com/nandorojo/dripsy/issues/23

**Comment by nandorojo** [comment]
2 updates here: 

1. `3.2.0` themifies any color props on `TextInput`
2. `3.2.0` adds `contentContainerSx` to `ScrollView`
3. You can use the `useSx` hook to add `sx` to any component. I added docs for this at [dripsy.xyz/apis/useSx](https://www.dripsy.xyz/apis/useSx)
