### ISSUE TITLE
useResponsiveValue hook

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/dripsy#9]
Can be tied with the current `useBreakpointIndex` hook in `src/css`.

Reference: https://github.com/system-ui/theme-ui/tree/master/packages/match-media

**Comment by cmaycumber** [comment]
Looking at the implementation of the theme-ui one this seems like something that will be easy to knock out since you've already created the useBreakpointIndex hook. 

I don't mind picking up a PR for it if it's something you aren't already starting.

**Comment by nandorojo** [comment]
I haven't started it yet, that would be awesome!
