### ISSUE TITLE
Dripsy not using color modes

### ISSUE THREAD

**Issue by hi019** [nandorojo/dripsy#91]
Hello, I'm having issues with dark and light values not being applied. [Here](hhttps://snack.expo.io/6KbcMwcIi) is a small snack showing the problem. The color scheme is set to light so the text should be blue, but instead it is red.

I also think there should be a color mode example in this repo, when this is resolved I can make a PR.

**Comment by nandorojo** [comment]
Hey I think the move is to avoid our color modes and just handle it with React context yourself, and edit the theme at the root of your app

**Comment by nandorojo** [comment]
That's how restyle does it

**Comment by hi019** [comment]
Got it, thanks.
