### ISSUE TITLE
Is it possible to use Dripsy with CRA?

### ISSUE THREAD

**Issue by harrisrobin** [nandorojo/dripsy#92]
Hi,
first of all, thanks for creating this, it looks awesome. 

In the readme, I see a section covering next.js & expo, but nothing about CRA. Has anyone managed to get this working with CRA? I have `craco` setup to customize CRA but I'm not quite sure how I would add a babel preset like the error below is suggesting.

Currently, I get the following if I attempt to run the app:
![image](https://user-images.githubusercontent.com/3880008/116015164-4053d480-a5ed-11eb-8e1a-dbefae38a97f.png)

Any help is greatly appreciated 😄

**Comment by nandorojo** [comment]
If you're using CRA without any React Native app, you might be better off just using theme-ui.

**Comment by harrisrobin** [comment]
> If you're using CRA without any React Native app, you might be better off just using theme-ui.

I'm using CRA with react-native-web and my plan is to have another package with React Native and use `dripsy` to share components in a monorepo. Does that make sense? I'd love to use dripsy as I intend to use `react-native`

**Comment by nandorojo** [comment]
Does CRA let you add Babel plugins or customize webpack? I'm not sure how CRA works, but judging by the error message it seems like you need to add that to your Babel config.

**Comment by nandorojo** [comment]
Maybe try this and add the Babel plugins?

https://devinschulz.com/modify-create-react-apps-babel-configuration-without-ejecting/

**Comment by harrisrobin** [comment]
> Maybe try this and add the Babel plugins?
> 
> https://devinschulz.com/modify-create-react-apps-babel-configuration-without-ejecting/

Thanks for the reply @nandorojo I'll try it this week and let you know how it goes

**Comment by harrisrobin** [comment]
@nandorojo looks like the way to make it work with CRA is to set `DISABLE_NEW_JSX_TRANSFORM=true` in the .env file. Dripsy doesn't use @jsx pragma so we can't use the new JSX runtime.

Thanks to @janicduplessis for helping me figure this out, props to you!

Closing this since it's resolved and hopefully this helps anyone else using CRA.

**Comment by keithpickering** [comment]
@harrisrobin Can you provide more details on how you solved this? I created an `.env` file with `DISABLE_NEW_JSX_TRANSFORM=true` but I still get the JSX error at runtime
