### ISSUE TITLE
TextInput events have untyped callback arguments

### ISSUE THREAD

**Issue by JackCA** [nandorojo/dripsy#99]
It appears that the events on a `TextInput` imported from Dripsy lose their typed callback arguments:

### From Dripsy
![CleanShot 2021-05-07 at 10 32 38](https://user-images.githubusercontent.com/296167/117487576-1e791c80-af20-11eb-9510-8e5c4255a040.png)

### From react-native
![CleanShot 2021-05-07 at 10 33 03](https://user-images.githubusercontent.com/296167/117487596-26d15780-af20-11eb-84f6-ea36c7a206c0.png)

I tried digging into `createThemedComponent` but didn't see an obvious issue. Perhaps, it's a limitation of Typescript?

**Comment by nandorojo** [comment]
Mmmm let me look into this, I don't think I have this issue. What version?

**Comment by JackCA** [comment]
v1.5.16

**Comment by nandorojo** [comment]
<img width="1049" alt="Screen Shot 2021-05-07 at 1 44 28 PM" src="https://user-images.githubusercontent.com/13172299/117488392-5a20e000-af3a-11eb-939d-db9ea653ba20.png">

Works for me

**Comment by JackCA** [comment]
What version of typescript are you on? Maybe that's the issue. I am on 4.2.3

**Comment by nandorojo** [comment]
Same here.

**Comment by JackCA** [comment]
I think the issue is actually the fact that I am using a `useCallback` and it doesn't infer the types properly... apologies for another misdirect
